!> \brief CVODE interface for detailed chemistry calculation
! CALL CVODE FOR SOLVING CHEMISTRY 
! THE DERIVATIVE AND JACOBIAN FUNCTION TRACK N_TRACKED_SPECIES+2
! VARIABLES. THE +2 IS TEMPERATURE AND PRESSURE.

!> @cond DOXYGEN_IGNORE
#ifdef WITH_SUNDIALS
!> @endcond


MODULE CVODE_INTERFACE

USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS   
USE TYPES
USE CHEMCONS
USE PROPERTY_DATA
USE, INTRINSIC :: ISO_C_BINDING
USE FSUNDIALS_CORE_MOD

IMPLICIT NONE

TYPE :: USERDATA
    REAL(EB) :: ZETA0 ! initial unmixed fraction
    REAL(EB) :: TAU_MIX ! Mixing time scale
    REAL(EB) :: CELL_MASS ! Total mass of the cell (mixed + unmixed)
    REAL(EB), ALLOCATABLE, DIMENSION(:) :: ZZ_UNMIXED  ! Initial mass fraction or mass fraction of unmixed zone.
    REAL(EB), ALLOCATABLE, DIMENSION(:) :: ZZ_CELL  ! Initial mass fraction of cell.
    REAL(EB) :: H_IN ! Enthalpy of the intial mass fraction
    REAL(EB) :: EQUIL_TMP !EQUIL_TMP is the maximul temperature mixing zone can reach, after which dT/dt=0
    REAL(EB) :: TMP_UNMIX
    LOGICAL  :: USE_DTMPDT_LIMITER=.FALSE.
    REAL(EB) :: SMOOTH_DELTA=10.0_EB
END TYPE USERDATA

LOGICAL :: DEBUG=.FALSE.
REAL(EB), PARAMETER :: MIN_CHEM_TMP=200._EB
REAL(EB) :: CUR_CFD_TIME

PUBLIC CVODE_SERIAL

CONTAINS


!> \brief The right hand side function of the ode d[c]/dt = wdot (=f).
!> \param TN_C is the current time
!> \param SUNVEC_Y is the current array of molar concentrations, temperature and pressure.
!> \param SUNVEC_F is the array of derivatives returned
!> \param C_USER_DATA is the user data array. Hold unburned zone data for mixing+chem.
!> \details The right hand side function of the ode d[c]/dt = wdot (=f). Provides the Derivative function to CVODE.
INTEGER(C_INT) FUNCTION RHSFN(TN_C, SUNVEC_Y, SUNVEC_F, C_USER_DATA) &
    RESULT(IERR) BIND(C,NAME='RHSFN')


! CALLING VARIABLES
REAL(C_DOUBLE), VALUE :: TN_C      ! CURRENT TIME
TYPE(N_VECTOR)        :: SUNVEC_Y  ! SOLUTION N_VECTOR
TYPE(N_VECTOR)        :: SUNVEC_F  ! RHS N_VECTOR
TYPE(C_PTR),    VALUE :: C_USER_DATA ! USER-DEFINED DATA

! POINTERS TO DATA IN SUNDIALS VECTORS
REAL(EB) :: TN ! Current time
REAL(EB), POINTER :: CVEC(:)
REAL(EB), POINTER :: FVEC(:)
TYPE(USERDATA), POINTER :: USER_DATA

! TO PREVENT UNUSED VARIABLE WARNING
IF (DEBUG) THEN
   WRITE(LU_ERR,*)"TIME = ",TN_C
   IF (.NOT. C_ASSOCIATED(C_USER_DATA)) WRITE(LU_ERR,*)" NO USER_DATA IS PROVIDED"
ENDIF

! GET DATA ARRAYS FROM SUNDIALS VECTORS
TN = REAL(TN_C, KIND=KIND(EB)) 
CVEC => FN_VGETARRAYPOINTER(SUNVEC_Y)
FVEC => FN_VGETARRAYPOINTER(SUNVEC_F)

CALL C_F_POINTER(C_USER_DATA, USER_DATA)

FVEC = 0._EB
CALL DERIVATIVE(CVEC, FVEC, TN, USER_DATA)


IERR = 0
RETURN

END FUNCTION RHSFN



!> \brief Calculate derivative (fvec) for a given concentration vector cvec(n_tracked_species+2)
!> \param CVEC is the current array of molar concentrations, temperature and pressure.
!> \param FVEC is the array of derivatives returned
!> \param TN is the current time
!> \param USER_DATA is the user data array. Hold unburned zone data for mixing+chem.

SUBROUTINE DERIVATIVE(CVEC,FVEC, TN, USER_DATA)
USE PHYSICAL_FUNCTIONS, ONLY : GET_SPECIFIC_HEAT_INTERP, GET_ENTHALPY, GET_ENTHALPY_Z, &
         MOLAR_CONC_TO_MASS_FRAC, GET_MOLECULAR_WEIGHT
!USE CHEM_EQUIL, ONLY : EQUILIBRATE

REAL(EB), POINTER, INTENT(INOUT)  :: CVEC(:)
REAL(EB), POINTER, INTENT(INOUT) :: FVEC(:)
REAL(EB), INTENT(IN) :: TN
TYPE(USERDATA), INTENT(IN):: USER_DATA

REAL(EB) :: R_F,MIN_SPEC(N_TRACKED_SPECIES), KG,  TMP, RHO, &
          K_0, K_INF, P_RI, FCENT, B_I, RRTMP, THIRD_BODY_ENHANCEMENT, PRES
INTEGER :: I,NS, ITMP
REAL(EB) :: ZZ(N_TRACKED_SPECIES), CP, HS_I, DG, TMPI
REAL(EB) :: ZZ_MIXED(N_TRACKED_SPECIES)
REAL(EB) :: ZETA, MIXING_FACTOR, VOL_CHANGE_TERM, SUM_OMEGA_DOT, SUM_CC, MW0, MW, SUM_H_ZZ0, EXPONENT, &
            CONC, LOSS_FACTOR, RAD_LOSS, LIMITER,EQL_TMP,PRES_OUT
TYPE(REACTION_TYPE), POINTER :: RN

TMP = MAX(CVEC(N_TRACKED_SPECIES+1), MIN_CHEM_TMP)
TMPI = 1._EB/TMP
PRES = CVEC(N_TRACKED_SPECIES+2) ! PA
RRTMP = 1._EB/(R0*TMP)
ZETA = USER_DATA%ZETA0*EXP(-TN/USER_DATA%TAU_MIX)
MIXING_FACTOR = 0._EB
LOSS_FACTOR = 1.0_EB - HEAT_LOSS_FACTOR
RAD_LOSS = RAD_LOSS_FACTOR*SIGMA*TMP**4
IF (ZETA < 1._EB) MIXING_FACTOR = ZETA/(1-ZETA)/USER_DATA%TAU_MIX

CALL GET_MOLECULAR_WEIGHT(USER_DATA%ZZ_UNMIXED,MW0)
IF (ANY(CVEC(1:N_TRACKED_SPECIES) >0)) THEN 
   RHO = DOT_PRODUCT(SPECIES_MIXTURE(1:N_TRACKED_SPECIES)%MW,CVEC(1:N_TRACKED_SPECIES))
   CALL MOLAR_CONC_TO_MASS_FRAC(CVEC(1:N_TRACKED_SPECIES), ZZ(1:N_TRACKED_SPECIES))
   CALL GET_MOLECULAR_WEIGHT(ZZ(1:N_TRACKED_SPECIES),MW)
ELSE ! Enters at the first timestep when ZETA0=1.
   RHO = PRES*MW0/R0/TMP
   MW = MW0
   ZZ(1:N_TRACKED_SPECIES) = USER_DATA%ZZ_UNMIXED(1:N_TRACKED_SPECIES)
ENDIF
MIN_SPEC = SPECIES_MIXTURE%ODE_REL_ERROR*ZZ_MIN_GLOBAL

REACTION_LOOP: DO I=1,N_REACTIONS
   RN => REACTION(I)
   ! CHECK FOR CONSUMED SPECIES
   DO NS=1,RN%N_SMIX_FR
      IF (RN%NU_MW_O_MW_F_FR(NS) < 0._EB .AND. CVEC(RN%NU_INDEX(NS)) < MIN_SPEC(NS)) CYCLE REACTION_LOOP
   ENDDO

   ! CALCULATE FORWARD RATE COEFF.
   K_INF = RN%A_SI*TMP**RN%N_T*EXP(-RN%E*RRTMP) !A_SI IS IN [KMOL/M3]^() UNIT.
   R_F = K_INF
   IF(RN%REVERSE) THEN ! COMPUTE EQUILIBRIUM CONSTANT
      ITMP = MAX(MIN(I_MAX_TEMP-1,INT(TMP)),0)
      DG = RN%DELTA_G(ITMP) + (TMP-REAL(ITMP,EB))*(RN%DELTA_G(ITMP+1)-RN%DELTA_G(ITMP))
      KG = EXP(DG/TMP)*(P_STP*RRTMP)**RN%C0_EXP
      R_F = R_F*KG ! KG IS THE CONCENTRATION EQUILIBRIUM CONSTANT OF REVERSE REACTION. 
   ENDIF

   ! MULTIPLY WITH MOLAR_CONCENTRATION ^ STOICHIOMETRIC_COEFF
   DO NS=1,RN%N_SPEC
      IF (CVEC(YP2ZZ(RN%N_S_INDEX(NS))) < MIN_SPEC(YP2ZZ(RN%N_S_INDEX(NS)))) CYCLE REACTION_LOOP
      EXPONENT = RN%N_S(NS)
      CONC = CVEC(YP2ZZ(RN%N_S_INDEX(NS)))
      IF (EXPONENT < 1._EB) THEN
         R_F = R_F * CONC**(EXPONENT - 1._EB)
         R_F = R_F * CONC
      ELSE
          R_F = R_F * CONC**EXPONENT
      END IF
   ENDDO

   ! CALCULATE B_I BASED ON TYPE OF REACTION
   IF (RN%THIRD_BODY) THEN

      IF (RN%N_THIRD > 0) THEN
         THIRD_BODY_ENHANCEMENT = DOT_PRODUCT(CVEC(1:N_SPECIES),RN%THIRD_EFF(1:N_SPECIES))
      ELSE
         THIRD_BODY_ENHANCEMENT = PRES*RRTMP
      ENDIF

      IF (RN%REACTYPE==THREE_BODY_ARRHENIUS_TYPE) THEN
         R_F = R_F * THIRD_BODY_ENHANCEMENT
      ELSEIF(RN%REACTYPE==FALLOFF_LINDEMANN_TYPE .OR. RN%REACTYPE==FALLOFF_TROE_TYPE ) THEN
         K_0 = RN%A_LOW_PR*TMP**(RN%N_T_LOW_PR)*EXP(-RN%E_LOW_PR*RRTMP)
         P_RI = K_0/K_INF*THIRD_BODY_ENHANCEMENT
         FCENT = CALCFCENT(TMP,P_RI, I)
         B_I = P_RI/(1._EB+P_RI)*FCENT
         R_F = R_F * B_I
      ENDIF 
   ENDIF

   IF (RN%REACTYPE == ADSORPTION_TYPE) THEN
      B_I = RN%A_AD/(1+R_F)
      R_F = R_F*B_I
   ENDIF

   IF (DEBUG) WRITE(LU_ERR,*)"RN%ID, RATE-CONTRIB=", RN%ID, R_F

   ! ADD CONTRIBUTION OF THE REACTION TO THE FVEC
   DO NS=1,RN%N_SMIX_FR
     FVEC(RN%NU_INDEX(NS)) = FVEC(RN%NU_INDEX(NS)) + RN%NU_NN(RN%NU_INDEX(NS)) * R_F
   ENDDO

ENDDO REACTION_LOOP

! CALCULATE TEMPERATURE DERIVATIVE
CALL GET_SPECIFIC_HEAT_INTERP(ZZ(1:N_TRACKED_SPECIES),CP,TMP)
SUM_H_ZZ0 = 0._EB
DO NS=1,N_TRACKED_SPECIES
   CALL GET_ENTHALPY_Z(NS, TMP,HS_I)
   SUM_H_ZZ0 = SUM_H_ZZ0+HS_I*USER_DATA%ZZ_UNMIXED(NS) ! Needed later.
   HS_I = HS_I * SPECIES_MIXTURE(NS)%MW ! To convert J/kg to J/kmol (absolute enthalpy includes enthalpy of formation)
   FVEC(N_TRACKED_SPECIES+1)= FVEC(N_TRACKED_SPECIES+1) + HS_I*FVEC(NS)   
ENDDO
! The first term is due to chemistry production rate and the second term is due to mixing.
FVEC(N_TRACKED_SPECIES+1)=-(FVEC(N_TRACKED_SPECIES+1)*LOSS_FACTOR + RAD_LOSS &
                            + (RHO*(SUM_H_ZZ0-USER_DATA%H_IN))*MIXING_FACTOR)/RHO/CP

! Apply limiter
LIMITER = 1.0_EB
IF(USER_DATA%USE_DTMPDT_LIMITER) THEN
   ZZ_MIXED = (USER_DATA%ZZ_CELL-ZETA*USER_DATA%ZZ_UNMIXED)/(1.0_EB - ZETA)
   !CALL EQUILIBRATE(ZZ_MIXED, USER_DATA%TMP_UNMIX, PRES, EQL_TMP, PRES_OUT,1)
   LIMITER = 1.0_EB / (1.0_EB + EXP((TMP - EQL_TMP)/USER_DATA%SMOOTH_DELTA))
   FVEC(N_TRACKED_SPECIES+1) = FVEC(N_TRACKED_SPECIES+1) * LIMITER
ENDIF

! SO FAR FVEC(1:N_TRACKED_SPECIES) CONTAINS CHEMISTRY PRODUCTION RATE TERM (OMEGA_DOT). 
! THE FVEC(N_TRACKED_SPECIES+1) CONTAINS TOTAL TEMPERATURE DERIVATIVE (due to chemistry and mixing).

! NOW CALCULATE THE VOLUME CHANGE TERM
SUM_OMEGA_DOT = SUM(FVEC(1:N_TRACKED_SPECIES))
SUM_CC = SUM(CVEC(1:N_TRACKED_SPECIES))
VOL_CHANGE_TERM = 0._EB
IF (SUM_CC > 0._EB) THEN
   VOL_CHANGE_TERM = SUM_OMEGA_DOT/SUM_CC+TMPI*FVEC(N_TRACKED_SPECIES+1)+MW/MW0*MIXING_FACTOR
ENDIF

! ADD THE CONTRIBUTION DUE TO MIXING AND VOLUME CHANGE IN CONCENTRATION DERIVATIVE.
DO NS=1,N_TRACKED_SPECIES
   FVEC(NS) = FVEC(NS) + RHO * USER_DATA%ZZ_UNMIXED(NS)/SPECIES_MIXTURE(NS)%MW*MIXING_FACTOR - CVEC(NS)*VOL_CHANGE_TERM
ENDDO

! PRESSURE DERIVATIVE (CONSTANT PRESSURE ASSUMPTION)
FVEC(N_TRACKED_SPECIES+2) = 0._EB

END SUBROUTINE DERIVATIVE


!> \brief Calculate fall-off function 
!> \param TMP is the current temperature.
!> \param P_RI is the reduced pressure
!> \param RNI is the index of reaction

REAL(EB) FUNCTION CALCFCENT(TMP, P_RI, RNI)
REAL(EB), INTENT(IN) :: TMP, P_RI
INTEGER, INTENT(IN) :: RNI
TYPE(REACTION_TYPE), POINTER :: RN
REAL(EB) :: LOGFCENT, C, N, LOGPRC
REAL(EB), PARAMETER :: D=0.14_EB

RN => REACTION(RNI)
IF(RN%REACTYPE==FALLOFF_TROE_TYPE) THEN
   IF (RN%T2_TROE <-1.E20_EB) THEN
      LOGFCENT = LOG10(MAX((1 - RN%A_TROE)*EXP(-TMP*RN%RT3_TROE) + &
                 RN%A_TROE*EXP(-TMP*RN%RT1_TROE),TWO_EPSILON_EB))
   ELSE
      LOGFCENT = LOG10(MAX((1 - RN%A_TROE)*EXP(-TMP*RN%RT3_TROE) + &
                 RN%A_TROE*EXP(-TMP*RN%RT1_TROE) + EXP(-RN%T2_TROE/TMP),TWO_EPSILON_EB))
   ENDIF
   C = -0.4_EB - 0.67_EB*LOGFCENT
   N = 0.75_EB - 1.27_EB*LOGFCENT
   LOGPRC = LOG10(MAX(P_RI, TWO_EPSILON_EB)) + C
   CALCFCENT = 10._EB**(LOGFCENT/(1._EB + (LOGPRC/(N - D*LOGPRC))**2))
ELSE
   CALCFCENT = 1._EB  !FALLOFF-LINDEMANNN
ENDIF

RETURN

END FUNCTION CALCFCENT




!> \brief The jacobian of the ode right hand side function j = df/dy
!> \param TN_C is the current time provided by CVODE during callback, not the actual CFD time.
!> \param SUNVEC_Y is the current array of molar concentrations, temperature and pressure.
!> \param SUNVEC_F is the array of derivatives returned
!> \param SUNMAT_J is the Jacobian array returned to CVODE
!> \param C_USER_DATA is the user data array. Hold unburned zone data for mixing+chem.
!> \param TMP1 is not yet used in FDS.
!> \param TMP2 is not yet used in FDS.
!> \param TMP3 is not yet used in FDS.
!> \details The jacobian of the ode right hand side function j = df/dy. Provides the Jacobian function to CVODE.

INTEGER(C_INT) FUNCTION JACFN(TN_C, SUNVEC_Y, SUNVEC_F, SUNMAT_J, &
 C_USER_DATA, TMP1, TMP2, TMP3) &
 RESULT(IERR) BIND(C,NAME='JACFN')

USE FSUNMATRIX_DENSE_MOD

! CALLING VARIABLES
REAL(C_DOUBLE), VALUE :: TN_C             ! CURRENT TIME
TYPE(N_VECTOR)        :: SUNVEC_Y         ! CURRENT SOLUTION N_VECTOR
TYPE(N_VECTOR)        :: SUNVEC_F         ! CURRENT RHS N_VECTOR
TYPE(SUNMATRIX)       :: SUNMAT_J         ! JACOBIAN SUNMATRIX
TYPE(C_PTR), VALUE    :: C_USER_DATA      ! USER-DEFINED DATA
TYPE(N_VECTOR)        :: TMP1, TMP2, TMP3 ! WORKSPACE N_VECTORS

! POINTER TO DATA IN SUNDIALS MATRIX
REAL(EB) :: TN ! Current time
REAL(EB), POINTER :: CVEC(:)
REAL(EB), POINTER :: FVEC(:)
REAL(EB), POINTER :: JMAT1D(:)
REAL(EB) :: JMAT(N_TRACKED_SPECIES+2, N_TRACKED_SPECIES+2)
REAL(EB), POINTER :: DUMMY(:)
TYPE(USERDATA), POINTER :: USER_DATA

INTEGER :: NS1, NS2, NEQ

! TO PREVENT UNUSED VARIABLE WARNING
IF(DEBUG) THEN
   WRITE(LU_ERR,*)" TIME= ",TN_C
   DUMMY => FN_VGETARRAYPOINTER(TMP1)
   DUMMY => FN_VGETARRAYPOINTER(TMP2)
   DUMMY => FN_VGETARRAYPOINTER(TMP3)
   IF (.NOT. C_ASSOCIATED(C_USER_DATA)) WRITE(LU_ERR,*)" NO USER_DATA IS PROVIDED"
ENDIF


! GET DATA ARRAYS FROM SUNDIALS VECTORS
TN = REAL(TN_C, KIND=KIND(EB))
CVEC => FN_VGETARRAYPOINTER(SUNVEC_Y)
FVEC => FN_VGETARRAYPOINTER(SUNVEC_F)
CALL C_F_POINTER(C_USER_DATA, USER_DATA)
JMAT = 0._EB
CALL JACOBIAN(CVEC, FVEC, JMAT, TN, USER_DATA)

NEQ = N_TRACKED_SPECIES +2
JMAT1D => FSUNDENSEMATRIX_DATA(SUNMAT_J)
DO NS1=1, NEQ
   DO NS2=1, NEQ
      JMAT1D((NS1-1)*NEQ+NS2)=JMAT(NS1,NS2)
   ENDDO
ENDDO

! RETURN SUCCESS
IERR = 0
RETURN

END FUNCTION JACFN


!> \brief Calculate the analytical jacobian jmat[n_tracked_species+2,n_tracked_species+2]
!> \param CVEC is the current array of molar concentrations, temperature and pressure.
!> \param FVEC is the array of derivatives passed as input
!> \param JMAT is the jacobian matrix returned
!> \param TN is the current time provided by CVODE during callback, not the actual CFD time.
!> \param USER_DATA is the user data array. Hold unburned zone data for mixing+chem.

SUBROUTINE JACOBIAN(CVEC,FVEC,JMAT,TN,USER_DATA)

USE PHYSICAL_FUNCTIONS, ONLY : GET_SPECIFIC_HEAT_INTERP, GET_SPECIFIC_HEAT_Z,  GET_ENTHALPY, & 
             GET_ENTHALPY_Z, GET_SPECIFIC_HEAT_TMP_DERIVATIVE, MOLAR_CONC_TO_MASS_FRAC, GET_MOLECULAR_WEIGHT
!USE CHEM_EQUIL, ONLY : EQUILIBRATE

REAL(EB), POINTER, INTENT(INOUT) :: CVEC(:)
REAL(EB), POINTER, INTENT(INOUT) :: FVEC(:)
REAL(EB), INTENT(INOUT) :: JMAT(N_TRACKED_SPECIES+2, N_TRACKED_SPECIES+2)
REAL(EB), INTENT(IN) :: TN
TYPE(USERDATA), INTENT(IN):: USER_DATA

REAL(EB) :: R_F,R_F_DUP,DCVEC1,DCVEC2, MIN_SPEC(N_TRACKED_SPECIES), KG,  TMP, RHO, &
            K_0, K_INF, P_RI, FCENT, B_I, RRTMP, THIRD_BODY_ENHANCEMENT, PRES
REAL(EB) :: ZZ(N_TRACKED_SPECIES), CP_I(N_TRACKED_SPECIES), HS_I(N_TRACKED_SPECIES)
REAL(EB) :: ZZ_MIXED(N_TRACKED_SPECIES)
REAL(EB) :: DKCDTBYKC, DBIDC(N_TRACKED_SPECIES), DBIDT, CP, DCPDT, DKINFDTMPBYKINF, DTMPDT, DG, TMPI, RHOI, CPI
REAL(EB) :: ZETA, MIXING_FACTOR, SUM_OMEGA_DOT, SUM_CC, SUM_OMEGA_DOT_BY_CC, SUM_CC_I, ENRG_TERM, DUMMY1, DUMMY2, DUMMY3
REAL(EB) :: VOL_CHANGE_TERM1, VOL_CHANGE_TERM2, VOL_CHANGE_TERM3, VOL_CHANGE_TERM, SUM_DOMEGA_DOT_BY_DT, MW0, MW, &
            SUM_CP_ZZ0,SUM_H_ZZ0, EXPONENT, CONC, CONC_EXP, DRIDC, DRIDT, LOSS_FACTOR,RAD_LOSS,LIMITER, DLIMITER_DTMP, &
            DLIMITER_DC,EQL_TMP, PRES_OUT
INTEGER :: I,NS, NS1, NS2, ITMP
TYPE(REACTION_TYPE), POINTER :: RN

TMP = MAX(CVEC(N_TRACKED_SPECIES+1), MIN_CHEM_TMP)
TMPI = 1._EB/TMP
PRES = CVEC(N_TRACKED_SPECIES+2) ! PA
RRTMP = 1._EB/(R0*TMP)
ZETA = USER_DATA%ZETA0*EXP(-TN/USER_DATA%TAU_MIX)
MIXING_FACTOR = 0._EB
LOSS_FACTOR = 1.0_EB - HEAT_LOSS_FACTOR
RAD_LOSS = RAD_LOSS_FACTOR*SIGMA*TMP**4
IF (ZETA < 1._EB) MIXING_FACTOR = ZETA/(1-ZETA)/USER_DATA%TAU_MIX

CALL GET_MOLECULAR_WEIGHT(USER_DATA%ZZ_UNMIXED,MW0)
IF (ANY(CVEC(1:N_TRACKED_SPECIES) >0)) THEN 
   RHO = DOT_PRODUCT(SPECIES_MIXTURE(1:N_TRACKED_SPECIES)%MW,CVEC(1:N_TRACKED_SPECIES))
   CALL MOLAR_CONC_TO_MASS_FRAC(CVEC(1:N_TRACKED_SPECIES), ZZ(1:N_TRACKED_SPECIES))
   CALL GET_MOLECULAR_WEIGHT(ZZ(1:N_TRACKED_SPECIES),MW)
ELSE ! Enters at the first timestep when ZETA0=1.
   RHO = PRES*MW0/R0/TMP
   MW = MW0
   ZZ(1:N_TRACKED_SPECIES) = USER_DATA%ZZ_UNMIXED(1:N_TRACKED_SPECIES)
ENDIF
RHOI = 1._EB/RHO
MIN_SPEC = SPECIES_MIXTURE%ODE_REL_ERROR*ZZ_MIN_GLOBAL

! TO PREVENT UNUSED VARIABLE WARNING
IF(DEBUG) WRITE(LU_ERR,*)" SIZE OF FVEC ARRAY=", SIZE(FVEC)

! CALCULATE D[X]DOT/D[X] AND D[X]DOT/DT - Take contributions from every reactions 
REACTION_LOOP: DO I=1,N_REACTIONS
   DBIDC = 0._EB
   DBIDT = 0._EB
   DRIDC = 0._EB
   DRIDT = 0._EB

   RN => REACTION(I)
   ! CHECK FOR CONSUMED SPECIES
   DO NS=1,RN%N_SMIX_FR
      IF (RN%NU_MW_O_MW_F_FR(NS) < 0._EB .AND. CVEC(RN%NU_INDEX(NS)) < MIN_SPEC(NS)) CYCLE REACTION_LOOP
   ENDDO

   ! CALCULATE FORWARD RATE COEFF.
   K_INF = RN%A_SI*TMP**RN%N_T*EXP(-RN%E*RRTMP) !A_SI IS IN [KMOL/M3]^() UNIT.
   R_F = K_INF
   DKINFDTMPBYKINF = (RN%N_T+RN%E*RRTMP)*TMPI
   IF(RN%REVERSE) THEN ! COMPUTE EQUILIBRIUM CONSTANT
      ITMP = MAX(MIN(I_MAX_TEMP-1,INT(TMP)),0)
      DG = RN%DELTA_G(ITMP) + (TMP-REAL(ITMP,EB))*(RN%DELTA_G(ITMP+1)-RN%DELTA_G(ITMP))
      KG = EXP(DG*TMPI)*(P_STP*RRTMP)**RN%C0_EXP
      R_F = R_F*KG ! KG IS THE CONCENTRATION EQUILIBRIUM CONSTANT OF REVERSE REACTION. 
      DKCDTBYKC = ((RN%DELTA_G(MIN(I_MAX_TEMP,NINT(TMP)))*TMPI + RN%DELTA_S(MIN(I_MAX_TEMP,NINT(TMP))))+RN%C0_EXP)*TMPI 
   ENDIF

   DO NS=1,RN%N_SPEC
      IF (CVEC(YP2ZZ(RN%N_S_INDEX(NS))) < MIN_SPEC(YP2ZZ(RN%N_S_INDEX(NS)))) CYCLE REACTION_LOOP
   ENDDO

   ! CALCULATE B_I BASED ON TYPE OF REACTION
   IF (RN%THIRD_BODY) THEN
      IF (RN%N_THIRD > 0) THEN
         THIRD_BODY_ENHANCEMENT =  DOT_PRODUCT(CVEC(1:N_SPECIES),RN%THIRD_EFF(1:N_SPECIES))
      ELSE
         THIRD_BODY_ENHANCEMENT = PRES*RRTMP
      ENDIF
      IF (RN%REACTYPE==THREE_BODY_ARRHENIUS_TYPE) THEN
         R_F = R_F * THIRD_BODY_ENHANCEMENT
         IF (THIRD_BODY_ENHANCEMENT > 0) THEN
            DO NS=1,N_TRACKED_SPECIES
               IF (RN%N_THIRD > 0) THEN
                  DBIDC(NS) = RN%THIRD_EFF(NS)/THIRD_BODY_ENHANCEMENT
               ELSE
                  DBIDC(NS) = 1._EB/THIRD_BODY_ENHANCEMENT
               ENDIF   
            ENDDO
         ENDIF   
         DBIDT = -TMPI
      ELSEIF(RN%REACTYPE==FALLOFF_LINDEMANN_TYPE .OR. RN%REACTYPE==FALLOFF_TROE_TYPE) THEN
         K_0 = RN%A_LOW_PR*TMP**(RN%N_T_LOW_PR)*EXP(-RN%E_LOW_PR*RRTMP)
         P_RI = K_0/K_INF*THIRD_BODY_ENHANCEMENT
         FCENT = CALCFCENT(TMP,P_RI, I)
         B_I = P_RI/(1._EB+P_RI)*FCENT
         R_F = R_F * B_I
         IF (THIRD_BODY_ENHANCEMENT > TWO_EPSILON_EB) THEN
            CALL CALC_FALLOFF_DBIDC_AND_DBIDT(TMP, I, K_0, K_INF, P_RI, FCENT, DBIDC, DBIDT)
         ENDIF 
      ENDIF 
   ENDIF

   ! CALCULATE THE REACTION RATE
   R_F_DUP = R_F
   DO NS=1,RN%N_SPEC
      EXPONENT = RN%N_S(NS)
      CONC = CVEC(YP2ZZ(RN%N_S_INDEX(NS)))
      IF (EXPONENT < 1._EB) THEN
         R_F_DUP = R_F_DUP * CONC**(EXPONENT - 1._EB)
         R_F_DUP = R_F_DUP * CONC
      ELSE
         R_F_DUP = R_F_DUP * CONC**EXPONENT
      END IF
   ENDDO

   IF (RN%REACTYPE == ADSORPTION_TYPE) THEN
      B_I = RN%A_AD/(1+R_F_DUP)
      R_F = R_F*B_I
      R_F_DUP = R_F_DUP*B_I
   ENDIF

   !Contribution of qi
   DO NS1 = 1, RN%N_SPEC
      ! MULTIPLY WITH MOLAR_CONCENTRATION ^ STOICHIOMETRIC_COEFF
      CONC_EXP = 1.0_EB
      DO NS2=1,RN%N_SPEC
         EXPONENT = RN%N_S(NS2)
         CONC = CVEC(YP2ZZ(RN%N_S_INDEX(NS2)))
         IF (NS2 == NS1) THEN
            CONC_EXP = CONC_EXP * MERGE((CONC+TWO_EPSILON_EB)**(EXPONENT - 1._EB), CONC**(EXPONENT - 1._EB), EXPONENT < 1._EB)
         ELSE
            IF (EXPONENT < 1._EB) THEN
               CONC_EXP = CONC_EXP * CONC * (CONC+TWO_EPSILON_EB)**(EXPONENT - 1._EB)
            ELSE
               CONC_EXP = CONC_EXP * CONC**EXPONENT
            END IF
         ENDIF
      ENDDO
      
      DRIDC = DRIDC+R_F*CONC_EXP*RN%N_S(NS1)
      
      DO NS=1,RN%N_SMIX_FR
         DCVEC1 = R_F*CONC_EXP*RN%NU_NN(RN%NU_INDEX(NS))*RN%N_S(NS1)
         JMAT((YP2ZZ(RN%N_S_INDEX(NS1))),RN%NU_INDEX(NS)) = &
         JMAT((YP2ZZ(RN%N_S_INDEX(NS1))),RN%NU_INDEX(NS))+ DCVEC1 
      ENDDO   
   ENDDO 

   DRIDT = -TMPI*(RN%RHO_EXPONENT+1) + DKINFDTMPBYKINF
   IF (RN%REACTYPE == ADSORPTION_TYPE) THEN
      DBIDC = - B_I**2/RN%A_AD*DRIDC
      DBIDT = - B_I**2/RN%A_AD*DRIDT
   ENDIF

   R_F = R_F_DUP

   ! Add contribution of C_I
   IF (RN%THIRD_BODY) THEN
      DO NS = 1,N_TRACKED_SPECIES
         IF (abs(DBIDC(NS)) > 0._EB) THEN
            DO NS1=1,RN%N_SMIX_FR
               DCVEC2 = R_F*RN%NU_NN(RN%NU_INDEX(NS1))
               JMAT(NS,(YP2ZZ(RN%NU_INDEX(NS1)))) = &
                   JMAT(NS,(YP2ZZ(RN%NU_INDEX(NS1))))+ DCVEC2 * DBIDC(NS) 
            ENDDO
         ENDIF      
      ENDDO   
   ENDIF   

   ! Populate D[X]DOT/DT
   DO NS=1,RN%N_SMIX_FR
      DCVEC2 = R_F*RN%NU_NN(RN%NU_INDEX(NS))
      JMAT(N_TRACKED_SPECIES+1,RN%NU_INDEX(NS)) = JMAT(N_TRACKED_SPECIES+1,RN%NU_INDEX(NS)) - &
         DCVEC2*TMPI*(RN%RHO_EXPONENT+1) + DCVEC2 * DBIDT
      IF(RN%REVERSE) THEN
         JMAT(N_TRACKED_SPECIES+1,RN%NU_INDEX(NS)) = JMAT(N_TRACKED_SPECIES+1,RN%NU_INDEX(NS)) + &
            DCVEC2*(DKINFDTMPBYKINF - DKCDTBYKC)
      ELSE
         JMAT(N_TRACKED_SPECIES+1,RN%NU_INDEX(NS)) = JMAT(N_TRACKED_SPECIES+1,RN%NU_INDEX(NS)) + &
            DCVEC2*DKINFDTMPBYKINF  
      ENDIF      

   ENDDO

ENDDO REACTION_LOOP

! CALCULATE DTDOT/D[X]
SUM_CC = SUM(CVEC(1:N_TRACKED_SPECIES))
DTMPDT = FVEC(N_TRACKED_SPECIES+1)
CALL GET_SPECIFIC_HEAT_INTERP(ZZ(1:N_TRACKED_SPECIES),CP,TMP)
CPI = 1._EB/CP
CALL GET_SPECIFIC_HEAT_TMP_DERIVATIVE(ZZ(1:N_TRACKED_SPECIES),DCPDT,TMP)
SUM_CP_ZZ0 = 0._EB
SUM_H_ZZ0 = 0._EB
DO NS=1,N_TRACKED_SPECIES ! Store the CP and HS 
   CALL GET_SPECIFIC_HEAT_Z(NS, CP_I(NS), TMP)
   CALL GET_ENTHALPY_Z(NS, TMP,HS_I(NS))
   SUM_CP_ZZ0 = SUM_CP_ZZ0+CP_I(NS)*USER_DATA%ZZ_UNMIXED(NS) ! Needed later.
   SUM_H_ZZ0 = SUM_H_ZZ0+HS_I(NS)*USER_DATA%ZZ_UNMIXED(NS) ! Needed later.
   CP_I(NS)=CP_I(NS)*SPECIES_MIXTURE(NS)%MW
   HS_I(NS)=HS_I(NS)*SPECIES_MIXTURE(NS)%MW
ENDDO   

DO NS=1,N_TRACKED_SPECIES
   DO NS2=1,N_TRACKED_SPECIES
      JMAT(NS, N_TRACKED_SPECIES+1) = JMAT(NS, N_TRACKED_SPECIES+1)  + &
         HS_I(NS2)*JMAT(NS,NS2)
   ENDDO
   JMAT(NS, N_TRACKED_SPECIES+1) = (-JMAT(NS, N_TRACKED_SPECIES+1)  + CP_I(NS)*DTMPDT)*LOSS_FACTOR 
   JMAT(NS, N_TRACKED_SPECIES+1) = JMAT(NS, N_TRACKED_SPECIES+1)  + (-CP_I(NS)/RHO/CP+4.0_EB/SUM_CC)*RAD_LOSS
   JMAT(NS, N_TRACKED_SPECIES+1) = JMAT(NS, N_TRACKED_SPECIES+1) / RHO/CP 
ENDDO
      
! CALCULATE DTDOT/DT
DO NS=1,N_TRACKED_SPECIES
   JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) = JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) + &
      CP_I(NS)*FVEC(NS) + HS_I(NS)*JMAT(N_TRACKED_SPECIES+1,NS)   
ENDDO   
JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) = JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) + &
   RHO*DCPDT*DTMPDT
JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) = -JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1)/RHO/CP
JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) = JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) + DTMPDT*TMPI
JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) = JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1)*LOSS_FACTOR  
JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) = JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1)+ &
                (-5.0_EB/TMP+DCPDT/CP)*RAD_LOSS/RHO/CP

! NOW ADD TERMS FOR MIXING AND VOLUME CHANGE
!--------------------------------------------
! SO FAR JMAT(1:N_TRACKED_SPECIES, 1:N_TRACKED_SPECIES) CONTAINS JACOBIAN OF CHEMISTRY PRODUCTION RATE d(OMEGA_K_DOT)/d[X]. 
! THE JMAT(1:N_TRACKED_SPECIES, N_TRACKED_SPECIES+1) CONTAINS DTDOT/D[X] ONLY FOR THE CHEMISTRY PRODUCTION RATE TERM.
! THE JMAT(N_TRACKED_SPECIES+1, 1:N_TRACKED_SPECIES) CONTAINS D[X]DOT/D[X] ONLY FOR THE CHEMISTRY PRODUCTION RATE TERM.
! THE JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) CONTAINS D[T]DOT/DT ONLY FOR THE CHEMISTRY PRODUCTION RATE TERM.

! NOW CALCULATE THE VOLUME CHANGE TERM
SUM_OMEGA_DOT = SUM(FVEC(1:N_TRACKED_SPECIES))
SUM_DOMEGA_DOT_BY_DT = SUM(JMAT(N_TRACKED_SPECIES+1,1:N_TRACKED_SPECIES))
VOL_CHANGE_TERM1 = 0._EB
VOL_CHANGE_TERM2 = 0._EB
VOL_CHANGE_TERM = 0._EB
SUM_CC_I = 0._EB
IF (SUM_CC > 0._EB) THEN
   SUM_CC_I = 1._EB/SUM_CC
   VOL_CHANGE_TERM1 = SUM_OMEGA_DOT*SUM_CC_I
   VOL_CHANGE_TERM2 = TMPI*FVEC(N_TRACKED_SPECIES+1)
   VOL_CHANGE_TERM3 = MW/MW0*MIXING_FACTOR
   VOL_CHANGE_TERM = VOL_CHANGE_TERM1 + VOL_CHANGE_TERM2 + VOL_CHANGE_TERM3
ENDIF

! DTDOT/D[X]
ENRG_TERM = SUM_H_ZZ0-USER_DATA%H_IN
DUMMY3 = ENRG_TERM*MIXING_FACTOR*CPI*CPI*RHOI
DO NS=1,N_TRACKED_SPECIES
   DUMMY1 = DUMMY3*(CP*SPECIES_MIXTURE(NS)%MW-CP_I(NS))
   JMAT(NS, N_TRACKED_SPECIES+1) = JMAT(NS, N_TRACKED_SPECIES+1) - DUMMY1
ENDDO

! DTDOT/DT
DUMMY1 = ENRG_TERM*CPI*DCPDT
JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) = JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) &
         - MIXING_FACTOR*CPI*(SUM_CP_ZZ0+DUMMY1)

! Apply limiter
LIMITER = 1.0_EB
IF(USER_DATA%USE_DTMPDT_LIMITER) THEN
   ZZ_MIXED = (USER_DATA%ZZ_CELL-ZETA*USER_DATA%ZZ_UNMIXED)/(1.0_EB - ZETA)
   !CALL EQUILIBRATE(ZZ_MIXED, USER_DATA%TMP_UNMIX, PRES, EQL_TMP, PRES_OUT,1)
   LIMITER = 1.0_EB / (1.0_EB + EXP((TMP - EQL_TMP)/USER_DATA%SMOOTH_DELTA))

   DLIMITER_DTMP= - 1.0_EB/USER_DATA%SMOOTH_DELTA*LIMITER*(1.0_EB - LIMITER)
   JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1) = FVEC(N_TRACKED_SPECIES+1)* DLIMITER_DTMP + &
                     LIMITER * JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1)
   DLIMITER_DC = 1.0_EB/USER_DATA%SMOOTH_DELTA*LIMITER*(1.0_EB - LIMITER)*TMP*SUM_CC_I
   DO NS=1,N_TRACKED_SPECIES
      JMAT(NS, N_TRACKED_SPECIES+1) = FVEC(N_TRACKED_SPECIES+1)*DLIMITER_DC + &
               LIMITER * JMAT(NS, N_TRACKED_SPECIES+1)
   ENDDO
ENDIF

! ! D[X]DOT/D[X] 
DUMMY1 = SUM_CC_I*FVEC(N_TRACKED_SPECIES+1)
DUMMY2 = MIXING_FACTOR/MW0*SUM_CC_I
DO NS=1,N_TRACKED_SPECIES
   SUM_OMEGA_DOT_BY_CC= SUM(JMAT(NS,1:N_TRACKED_SPECIES))
   DO NS2=1,N_TRACKED_SPECIES
      ! Mixing term
      JMAT(NS, NS2) = JMAT(NS, NS2) + SPECIES_MIXTURE(NS)%MW/SPECIES_MIXTURE(NS2)%MW*MIXING_FACTOR*USER_DATA%ZZ_UNMIXED(NS2) 
      ! Volume change term
      IF (NS == NS2) THEN
         JMAT(NS, NS2) = JMAT(NS, NS2) - VOL_CHANGE_TERM
      ENDIF
      JMAT(NS, NS2) = JMAT(NS, NS2) - CVEC(NS2) * (SUM_CC_I*(SUM_OMEGA_DOT_BY_CC-VOL_CHANGE_TERM1) &
               + TMPI*(JMAT(NS, N_TRACKED_SPECIES+1) + DUMMY1) + (SPECIES_MIXTURE(NS)%MW-MW)*DUMMY2)
   ENDDO
ENDDO

! D[X]DOT/DT  
DUMMY1 = 0._EB
IF (SUM_CC >0) DUMMY1= DUMMY1+SUM_DOMEGA_DOT_BY_DT/SUM_CC
DUMMY1 = DUMMY1+TMPI*JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1)-2*TMPI*TMPI*FVEC(N_TRACKED_SPECIES+1)
DUMMY2 = RHO*TMPI
DO NS=1,N_TRACKED_SPECIES
   JMAT(N_TRACKED_SPECIES+1,NS) = JMAT(N_TRACKED_SPECIES+1,NS) - &
               DUMMY2*USER_DATA%ZZ_UNMIXED(NS)/SPECIES_MIXTURE(NS)%MW*MIXING_FACTOR 
   JMAT(N_TRACKED_SPECIES+1,NS) = JMAT(N_TRACKED_SPECIES+1,NS) - CVEC(NS)* DUMMY1
ENDDO


! CALL PRINT_JMAT(JMAT)


END SUBROUTINE JACOBIAN


!> \brief Print the component of jacobian matrix
!> \param JMAT is the Jacobian matrix.
SUBROUTINE PRINT_JMAT(JMAT)
REAL(EB), INTENT(IN) :: JMAT(N_TRACKED_SPECIES+2, N_TRACKED_SPECIES+2)
INTEGER :: NS, NS2

WRITE(LU_ERR,*)"------------------------------------------------------"
WRITE(LU_ERR,*)" Printing D[X]DOT/D[X] Jacobian elements...."
WRITE(LU_ERR,*)"------------------------------------------------------"
DO NS=1,N_TRACKED_SPECIES
   DO NS2=1,N_TRACKED_SPECIES
      IF (ABS(JMAT(NS,NS2)) > 0._EB) THEN
         WRITE(LU_ERR,'(A,2I4,5A,ES18.6)') "I,J=",NS, NS2, &
            " D[",TRIM(SPECIES_MIXTURE(NS2)%ID),"]DOT/D[",TRIM(SPECIES_MIXTURE(NS)%ID),"]=",JMAT(NS,NS2)
      ENDIF   
   ENDDO   
ENDDO

WRITE(LU_ERR,*)"------------------------------------------------------"
WRITE(LU_ERR,*)" Printing D[X]DOT/DT Jacobian elements...."
WRITE(LU_ERR,*)"------------------------------------------------------"
DO NS=1,N_TRACKED_SPECIES
   IF (ABS(JMAT(N_TRACKED_SPECIES+1,NS)) > 0._EB) THEN
      WRITE(LU_ERR,'(A,2I4,3A,ES18.6)') "I,J=",N_TRACKED_SPECIES+1, NS, &
         " D[",TRIM(SPECIES_MIXTURE(NS)%ID),"]DOT/D[T]=",JMAT(N_TRACKED_SPECIES+1,NS)
   ENDIF   
ENDDO

WRITE(LU_ERR,*)"------------------------------------------------------"
WRITE(LU_ERR,*)" Printing DTDOT/D[X] Jacobian elements...."
WRITE(LU_ERR,*)"------------------------------------------------------"
DO NS=1,N_TRACKED_SPECIES
   IF (ABS(JMAT(NS, N_TRACKED_SPECIES+1)) > 0._EB) THEN
      WRITE(LU_ERR,'(A,2I4,3A,ES18.6)') "I,J=",NS, N_TRACKED_SPECIES+1, &
         " D[T]DOT/D[",TRIM(SPECIES_MIXTURE(NS)%ID),"]=",JMAT(NS, N_TRACKED_SPECIES+1)
   ENDIF   
ENDDO

WRITE(LU_ERR,*)"------------------------------------------------------"
WRITE(LU_ERR,*)" Printing D[T]DOT/DT Jacobian elements...."
WRITE(LU_ERR,*)"------------------------------------------------------"
IF (ABS(JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1)) > 0._EB) THEN
   WRITE(LU_ERR,'(A,2I4,A,ES18.6)') "I,J=",N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1, &
      " D[T]DOT/D[T]=",JMAT(N_TRACKED_SPECIES+1, N_TRACKED_SPECIES+1)
ENDIF 
END SUBROUTINE PRINT_JMAT


!> \brief Calculate DBIDC of reactions 
!> \param TMP is the current temperature.
!> \param RNI is the reaction index.
!> \param K0 is the low pressure rate coeff.
!> \param KINF is the high pressure rate coeff.
!> \param P_RATIO is the pressure ratio.
!> \param F is the falloff function value.
!> \param DBIDC is the derivative of modification factor w.r.t concentration (out).
!> \param DBIDT is the derivative of modification factor w.r.t temperature (out).

SUBROUTINE CALC_FALLOFF_DBIDC_AND_DBIDT(TMP, RNI, K0, KINF, P_RATIO, F, DBIDC, DBIDT)
REAL(EB), INTENT(IN) :: TMP, P_RATIO, K0, KINF, F
INTEGER, INTENT(IN) :: RNI
REAL(EB), INTENT(INOUT) :: DBIDC(N_TRACKED_SPECIES)
REAL(EB), INTENT(INOUT) :: DBIDT
REAL(EB) :: DPRDBI, DFDBI, DPRDT, DFDT, RRTMP
INTEGER :: NS
TYPE(REACTION_TYPE), POINTER :: RN

RN => REACTION(RNI)
RRTMP = 1._EB/(R0*TMP)

DO NS=1,N_TRACKED_SPECIES
   IF (RN%N_THIRD>0) THEN
      DPRDBI = -RN%THIRD_EFF(NS)*K0/KINF
   ELSE
      DPRDBI = -1.0_EB*K0/KINF
   ENDIF
   DFDBI = 0._EB
   IF (RN%REACTYPE==FALLOFF_TROE_TYPE) THEN
      DFDBI = DDC_TROE(P_RATIO, F, DPRDBI, TMP, RNI)
   ENDIF   
   DBIDC(NS) = (DPRDBI/(P_RATIO*(1 + P_RATIO)) + DFDBI/F)
ENDDO


DPRDT = P_RATIO/TMP*( RN%N_T_LOW_PR + RN%E_LOW_PR*RRTMP - RN%N_T - RN%E*RRTMP - 1)
DFDT = 0._EB
IF (RN%REACTYPE==FALLOFF_TROE_TYPE) THEN
   DFDT = DDTMP_TROE(P_RATIO, F, DPRDT, TMP, RNI)
ENDIF   
DBIDT = (DPRDT/(P_RATIO*(1 + P_RATIO)) + DFDT/F)

RETURN
END SUBROUTINE CALC_FALLOFF_DBIDC_AND_DBIDT

!> \brief Calculate derivative of TROE function w.r.t concentration  
!> \param P_RATIO is the pressure ratio.
!> \param F is the falloff function value.
!> \param DPRDC is the derivative of TROE function w.r.t concentration.
!> \param TMP is the current temperature.
!> \param RNI is the reaction index
REAL(EB) FUNCTION DDC_TROE(P_RATIO, F, DPRDC, TMP, RNI) 
REAL(EB), INTENT(IN) :: P_RATIO, F, DPRDC, TMP
INTEGER, INTENT(IN) :: RNI
REAL(EB) :: LOGPR, LOGTEN, LOGFCENT, C, N, DLOGPRDC, DPARENTDC
TYPE(REACTION_TYPE), POINTER :: RN
REAL(EB), PARAMETER :: D=0.14_EB

RN => REACTION(RNI)
LOGPR = LOG10(MAX(P_RATIO,  TWO_EPSILON_EB))
LOGTEN = LOG(10.0)
IF (RN%T2_TROE <-1.E20_EB) THEN
   LOGFCENT = LOG10(MAX((1 - RN%A_TROE)*EXP(-TMP*RN%RT3_TROE) + &
              RN%A_TROE*EXP(-TMP*RN%RT1_TROE),TWO_EPSILON_EB))
ELSE
   LOGFCENT = LOG10(MAX((1 - RN%A_TROE)*EXP(-TMP*RN%RT3_TROE) + &
              RN%A_TROE*EXP(-TMP*RN%RT1_TROE) + EXP(-RN%T2_TROE/TMP),TWO_EPSILON_EB))
ENDIF

DLOGPRDC = DPRDC/P_RATIO/LOGTEN;
C = -0.4_EB - 0.67_EB*LOGFCENT
N = 0.75_EB - 1.27_EB*LOGFCENT

DPARENTDC = 2.0_EB*(LOGPR + C)/((N - D*(LOGPR + C))**2)*((DLOGPRDC)-(LOGPR + C)*(-D*(DLOGPRDC))/(N - D*(LOGPR + C)))

DDC_TROE = F*LOGTEN * (- LOGFCENT*DPARENTDC/(1.0 + ((LOGPR + C)/(N - D*(LOGPR + C)))**2)**2)

END FUNCTION DDC_TROE




!> \brief Calculate derivative of TROE function w.r.t temperature  
!> \param P_RATIO is the pressure ratio.
!> \param F is the falloff function value.
!> \param DPRDT is the derivative of TROE function w.r.t temperature.
!> \param TMP is the current temperature.
!> \param RNI is the reaction index
REAL(EB) FUNCTION DDTMP_TROE(P_RATIO, F, DPRDT, TMP, RNI) 
REAL(EB), INTENT(IN) :: P_RATIO, F, DPRDT, TMP
INTEGER, INTENT(IN) :: RNI
REAL(EB) :: FCENT, LOGPR, LOGTEN, LOGFCENT, DFCENTDT, C, N, DCDT, DNDT, DPARENTDT, DLOGFCENTDT, DLOGPRDT
TYPE(REACTION_TYPE), POINTER :: RN
REAL(EB), PARAMETER :: D=0.14_EB

RN => REACTION(RNI)
LOGPR = LOG10(MAX(P_RATIO, TWO_EPSILON_EB));
LOGTEN = LOG(10.0);
IF (RN%T2_TROE <-1.E20_EB) THEN
   FCENT = MAX((1 - RN%A_TROE)*EXP(-TMP*RN%RT3_TROE) + &
              RN%A_TROE*EXP(-TMP*RN%RT1_TROE),TWO_EPSILON_EB)
   DFCENTDT = (RN%A_TROE - 1)*EXP(-TMP*RN%RT3_TROE)*RN%RT3_TROE - &
              RN%A_TROE*EXP(-TMP*RN%RT1_TROE)*RN%RT1_TROE 
ELSE
   FCENT = MAX((1 - RN%A_TROE)*EXP(-TMP*RN%RT3_TROE) + &
              RN%A_TROE*EXP(-TMP*RN%RT1_TROE) + EXP(-RN%T2_TROE/TMP),TWO_EPSILON_EB)
   DFCENTDT = (RN%A_TROE - 1)*EXP(-TMP*RN%RT3_TROE)*RN%RT3_TROE - &
              RN%A_TROE*EXP(-TMP*RN%RT1_TROE)*RN%RT1_TROE + RN%T2_TROE*EXP(-RN%T2_TROE/TMP)/TMP**2
ENDIF
LOGFCENT = LOG10(FCENT)
DLOGFCENTDT = DFCENTDT/FCENT/LOGTEN;
C = -0.4_EB - 0.67_EB*LOGFCENT
N = 0.75_EB - 1.27_EB*LOGFCENT
DCDT = -0.67*DLOGFCENTDT
DNDT = -1.27*DLOGFCENTDT
DLOGPRDT = DPRDT/P_RATIO/LOGTEN

DPARENTDT = 2.0_EB*(LOGPR + C)/((N - D*(LOGPR + C))**2)* &
   ((DLOGPRDT + DCDT) - (LOGPR + C)*(DNDT - D*(DLOGPRDT + DCDT))/(N - D*(LOGPR + C)))

DDTMP_TROE = F*LOGTEN*(DLOGFCENTDT/(1.0 + ((LOGPR + C)/(N - D*(LOGPR + C)))**2) &
          - LOGFCENT*DPARENTDT/(1.0 + ((LOGPR + C)/(N - D*(LOGPR + C)))**2)**2)

END FUNCTION DDTMP_TROE



!> \brief cvode interface for ODE integrator. Call sundials cvode in serial mode.
!> \param CC species concentration (kmol/m3) array
!> \param ZZ_UNMIXED initial unmixed species mass fraction array (of the unbuned zone),needed for mixing+chem
!> \param ZZ_CELL initial cell species mass fraction array,needed for mixing+chem
!> \param TMP_IN is the temperature of the mixed zone (For DNS it is cell temp)
!> \param TMP_UNMIX is the unmix zone temperature
!> \param EQUIL_TMP is the maximul temperature mixing zone can reach, after which dT/dt=0
!> \param PR_IN is the pressure
!> \param ZETA0 is the initial unmixed fraction 
!> \param TAU_MIX is Mixing timescale
!> \param CELL_MASS total mass of the cell (mixed + unmixed)
!> \param TCUR is the start time in seconds
!> \param TEND is the end time in seconds
!> \param RTOL is the relative error for all the species (REAL_EB)
!> \param ATOL is the absolute error tolerance array for the species (REAL_EB)
!> \param TMP_OUT reactor calculated mixing zone temperature at the end
!> \param CHEM_TIME Chemical time scale
!> \param WRITE_SUBSTEPS Whether to write cvode substeps. Only write for first cfd step.
!> \param CVODE_CALL_OPTION 1:CV_NORMAL, 2=CV_ONE_STEP
!> \details This is the interface subroutine to the other modules.

SUBROUTINE CVODE_SERIAL(CC,ZZ_UNMIXED,ZZ_CELL,TMP_IN,TMP_UNMIX,EQUIL_TMP,USE_DTMPDT_LIMITER,PR_IN,ZETA0,TAU_MIX,CELL_MASS, &
                        TCUR,TEND,RTOL, ATOL,TMP_OUT, CHEM_TIME, WRITE_SUBSTEPS, CVODE_CALL_OPTION)
USE PHYSICAL_FUNCTIONS, ONLY : MOLAR_CONC_TO_MASS_FRAC, CALC_EQUIV_RATIO, GET_ENTHALPY, GET_MOLECULAR_WEIGHT
USE COMP_FUNCTIONS, ONLY: GET_FILE_NUMBER
USE CHEMCONS, ONLY: CVODE_WARNING_CELLS,CVODE_ERR_CODE_MIN,CVODE_ERR_CODE_MAX
USE GLOBAL_CONSTANTS
USE FCVODE_MOD                 ! FORTRAN INTERFACE TO CVODE
USE FNVECTOR_SERIAL_MOD        ! FORTRAN INTERFACE TO SERIAL N_VECTOR
USE FSUNMATRIX_DENSE_MOD       ! FORTRAN INTERFACE TO DENSE SUNMATRIX
USE FSUNLINSOL_DENSE_MOD       ! FORTRAN INTERFACE TO DENSE SUNLINEARSOLVER

REAL(EB), INTENT(INOUT) :: CC(N_TRACKED_SPECIES)
REAL(EB), INTENT(IN)    :: ZZ_UNMIXED(N_TRACKED_SPECIES),ZZ_CELL(N_TRACKED_SPECIES)
REAL(EB), INTENT(IN)    :: TMP_IN,TMP_UNMIX,PR_IN,ZETA0,TAU_MIX,CELL_MASS,TCUR,TEND,EQUIL_TMP
REAL(EB), INTENT(IN)    :: ATOL(N_TRACKED_SPECIES)
REAL(EB), INTENT(IN)    :: RTOL
REAL(EB), INTENT(OUT)   :: TMP_OUT,CHEM_TIME
INTEGER, INTENT(IN) :: CVODE_CALL_OPTION
LOGICAL, INTENT(IN) :: WRITE_SUBSTEPS,USE_DTMPDT_LIMITER

! C-INTERFACE VARIABLES
REAL(C_DOUBLE)                 :: TCUR_C(1)      ! CURRENT TIME
INTEGER(C_INT)                 :: IERR_C         ! ERROR FLAG FROM C FUNCTIONS
REAL(C_DOUBLE)                 :: RTOL_C         ! RELATIVE AND ABSOLUTE TOLERANCE
REAL(C_DOUBLE)                 :: CVEC_C(N_TRACKED_SPECIES+2)    ! N_SP + 2 (FOR TEMPERATURE AND PRESSURE)
REAL(C_DOUBLE)                 :: ATOLVEC_C(N_TRACKED_SPECIES+2) ! N_SP + 2 
INTEGER(C_LONG)                :: MAXSTEPS_C     ! MAXIMUM NUMBER OF INTERNAL STEPS
INTEGER(C_INT)                 :: MAXORD_C       ! Maximum number of order.
INTEGER(C_INT64_T)             :: NEQ
REAL(C_DOUBLE)                 :: CHEM_TIME_C(1)    ! OUTPUT CHEMICAL TIME

! SUNDIALS RELATED VARIABLES
TYPE(C_PTR)                    :: SUNCTX       ! SUNDIALS SIMULATION CONTEXT
TYPE(C_PTR)                    :: CVODE_MEM    ! CVODE MEMORY
TYPE(N_VECTOR),        POINTER :: SUNVEC_Y     ! SUNDIALS VECTOR
TYPE(SUNMATRIX),       POINTER :: SUNMAT_A     ! SUNDIALS MATRIX
TYPE(SUNLINEARSOLVER), POINTER :: SUNLINSOL_LS ! SUNDIALS LINEAR SOLVER
TYPE(N_VECTOR),        POINTER :: SUNATOL      ! SUNDIALS VECTOR FOR ABSOLUTE TOLERANCE
TYPE(C_PTR)                    :: USERDATAPTR  ! USER DATA CONTAINS MIXING INFORMATION

REAL(EB) :: ZZ(N_TRACKED_SPECIES), EQUIV, H_IN
INTEGER :: CVODE_TASK, NS, NTRY, MAXTRY, SUBSTEP_COUNT, MAXTRY_FAC
REAL(EB) :: H_G
TYPE(USERDATA), TARGET :: USER_DATA
LOGICAL :: ONLY_FIRST_STEP=.TRUE. ! Needed in CV_ONE_STEP


!======= INTERNALS ============
NEQ = INT(N_TRACKED_SPECIES+2, KIND(8))
TCUR_C = TCUR
CVEC_C(1:N_TRACKED_SPECIES) = CC
CVEC_C(N_TRACKED_SPECIES+1) = TMP_IN
CVEC_C(N_TRACKED_SPECIES+2) = PR_IN
ATOLVEC_C(1:N_TRACKED_SPECIES) = ATOL
ATOLVEC_C(N_TRACKED_SPECIES+1) = 0.001_EB
ATOLVEC_C(N_TRACKED_SPECIES+2) = 0.001_EB

! CREATE SUNDIALS CONTEXT
IERR_C = FSUNCONTEXT_CREATE(SUN_COMM_NULL, SUNCTX)

! CREATE SUNDIALS N_VECTOR
SUNVEC_Y => FN_VMAKE_SERIAL(NEQ, CVEC_C, SUNCTX)
IF (.NOT. ASSOCIATED(SUNVEC_Y)) THEN
   WRITE(LU_ERR,*) 'ERROR: SUNVEC = NULL'
   STOP 1
END IF

! CREATE A DENSE MATRIX
SUNMAT_A => FSUNDENSEMATRIX(NEQ, NEQ, SUNCTX)
IF (.NOT. ASSOCIATED(SUNMAT_A)) THEN
   WRITE(LU_ERR,*)'ERROR: SUNMAT = NULL'
   STOP 1
END IF

! CREATE A DENSE LINEAR SOLVER
SUNLINSOL_LS => FSUNLINSOL_DENSE(SUNVEC_Y, SUNMAT_A, SUNCTX)
IF (.NOT. ASSOCIATED(SUNLINSOL_LS)) THEN
   WRITE(LU_ERR,*) 'ERROR: SUNLINSOL = NULL'
   STOP 1
END IF

! CREATE CVODE MEMORY
CVODE_MEM = FCVODECREATE(CV_BDF, SUNCTX)
IF (.NOT. C_ASSOCIATED(CVODE_MEM)) THEN
   WRITE(LU_ERR,*) 'ERROR: CVODE_MEM = NULL'
   STOP 1
END IF

! INITIALIZE CVODE
IERR_C = FCVODEINIT(CVODE_MEM, C_FUNLOC(RHSFN), TCUR_C(1), SUNVEC_Y)
IF (IERR_C /= 0) THEN
   WRITE(LU_ERR,*) 'ERROR IN FCVODEINIT, IERR = ', IERR_C, '; HALTING'
   STOP 1
END IF

! SET RELATIVE AND ABSOLUTE TOLERANCES
RTOL_C = RTOL
SUNATOL => FN_VMAKE_SERIAL(NEQ, ATOLVEC_C, SUNCTX)
IERR_C = FCVODESVTOLERANCES(CVODE_MEM, RTOL_C, SUNATOL)
IF (IERR_C /= 0) THEN
   WRITE(LU_ERR,*) 'ERROR IN FCVODESSTOLERANCES, IERR = ', IERR_C, '; HALTING'
   STOP 1
END IF

! ATTACH LINEAR SOLVER
IERR_C = FCVODESETLINEARSOLVER(CVODE_MEM, SUNLINSOL_LS, SUNMAT_A);
IF (IERR_C /= 0) THEN
   WRITE(LU_ERR,*) 'ERROR IN FCVODESETLINEARSOLVER, IERR = ', IERR_C, '; HALTING'
   STOP 1
END IF

! SET JACOBIAN ROUTINE
IERR_C = FCVODESETJACFN(CVODE_MEM, C_FUNLOC(JACFN))
IF (IERR_C /= 0) THEN
   WRITE(LU_ERR,*) 'ERROR IN FCVODESETJACFN, IERR = ', IERR_C, '; HALTING'
   STOP 1
END IF

! SET MAX NUM OF STEPS
MAXSTEPS_C = MAX_CVODE_SUBSTEPS
IERR_C = FCVODESETMAXNUMSTEPS(CVODE_MEM, MAXSTEPS_C)
IF (IERR_C /= 0) THEN
   WRITE(LU_ERR,*) 'ERROR IN FCVODESETMAXNUMSTEPS, IERR = ', IERR_C, '; HALTING'
   STOP 1
END IF

! SET MAX ORDER
IF (CVODE_ORDER > 0) THEN
   MAXORD_C = CVODE_ORDER
   IERR_C = FCVODESETMAXORD(CVODE_MEM, MAXORD_C)
   IF (IERR_C /= 0) THEN
      WRITE(LU_ERR,*) 'ERROR IN FCVODESETMAXORD, IERR = ', IERR_C, '; HALTING'
      STOP 1
   END IF
ENDIF

! SET ERROR HANDLER
IERR_C = FSUNCONTEXT_PUSHERRHANDLER(SUNCTX, C_FUNLOC(FDS_CVODE_ERR_HANDLER), C_NULL_PTR)
IF (IERR_C /= 0) THEN
   WRITE(LU_ERR,*) 'ERROR IN FCVODESETMAXNUMSTEPS, IERR = ', IERR_C, '; HALTING'
   STOP 1
END IF

! SET USER DATA
USER_DATA%ZETA0 = ZETA0
USER_DATA%TAU_MIX = TAU_MIX
USER_DATA%CELL_MASS = CELL_MASS
ALLOCATE(USER_DATA%ZZ_UNMIXED(N_TRACKED_SPECIES))
USER_DATA%ZZ_UNMIXED = ZZ_UNMIXED
ALLOCATE(USER_DATA%ZZ_CELL(N_TRACKED_SPECIES))
USER_DATA%ZZ_CELL = ZZ_CELL
CALL GET_ENTHALPY(ZZ_UNMIXED,H_IN,TMP_UNMIX)
USER_DATA%H_IN = H_IN 
USER_DATA%EQUIL_TMP=EQUIL_TMP
USER_DATA%TMP_UNMIX=TMP_UNMIX
USER_DATA%USE_DTMPDT_LIMITER=USE_DTMPDT_LIMITER
USERDATAPTR = C_LOC(USER_DATA)
IERR_C = FCVODESETUSERDATA(CVODE_MEM, USERDATAPTR)

!CALL CVODE
CVODE_TASK = CV_NORMAL
IF(CVODE_CALL_OPTION ==2) THEN
   CVODE_TASK = CV_ONE_STEP
ENDIF

IF (CVODE_TASK == CV_NORMAL) THEN
   IERR_C = FCVODE(CVODE_MEM, TEND, SUNVEC_Y, TCUR_C, CVODE_TASK)
ELSE IF(CVODE_TASK == CV_ONE_STEP) THEN
   ONLY_FIRST_STEP = .TRUE.
   IF (WRITE_SUBSTEPS) THEN ! This WRITE_SUBSTEPS is only true for few verification cases.
      ONLY_FIRST_STEP = .FALSE.
      IF (.NOT. ALLOCATED(CVODE_SUBSTEP_DATA)) &
          ALLOCATE(CVODE_SUBSTEP_DATA((CVODE_MAX_TRY+1)*MAX_CVODE_SUBSTEPS, N_TRACKED_SPECIES+4))
   ENDIF
   
   SUBSTEP_COUNT = 0
   DO WHILE (TCUR_C(1) < TEND)
      SUBSTEP_COUNT = SUBSTEP_COUNT + 1
      IERR_C = FCVODE(CVODE_MEM, TEND, SUNVEC_Y, TCUR_C, CVODE_TASK)
      IF (IERR_C /= 0) THEN
         WRITE(LU_ERR,'(A, I4, A, 2E18.8, A)')" ERROR: CVODE didn't finish ODE solution in CV_ONE_STEP mode with message code:",&
                        IERR_C," and CUR_CFD_TIME, DT=", CUR_CFD_TIME, (TEND-TCUR), "."
         STOP
      ENDIF
      IF (ONLY_FIRST_STEP) EXIT 
      IF (WRITE_SUBSTEPS) THEN
         CALL MOLAR_CONC_TO_MASS_FRAC(CVEC_C(1:N_TRACKED_SPECIES), ZZ(1:N_TRACKED_SPECIES))
         CALL GET_ENTHALPY(ZZ(1:N_TRACKED_SPECIES),H_G,CVEC_C(N_TRACKED_SPECIES+1))
         CVODE_SUBSTEP_DATA(SUBSTEP_COUNT,1:4) = [TCUR_C(1), CVEC_C(N_TRACKED_SPECIES+1)-TMPM, CVEC_C(N_TRACKED_SPECIES+2), H_G]
         CVODE_SUBSTEP_DATA(SUBSTEP_COUNT,5:N_TRACKED_SPECIES+4) = ZZ(1:N_TRACKED_SPECIES)
      ENDIF  
   END DO

ENDIF

IF (IERR_C /= 0) THEN
   ! If all internal substeps are taken try two more times. This will allow larger CFD timestep.
   ! Make MAXTRY at least CVODE_MAX_TRY or for larger timestep (>1E-3) scale it proportionaly.
   MAXTRY_FAC = CEILING((TEND-TCUR)/1.0E-3_EB)
   MAXTRY_FAC = MIN(MAX(MAXTRY_FAC,1),50)
   MAXTRY = CVODE_MAX_TRY*MAXTRY_FAC
   IF (IERR_C == CV_TOO_MUCH_WORK) THEN !CV_TOO_MUCH_WORK == all internal substeps are taken
      NTRY = 0
      DO WHILE (NTRY < MAXTRY)
         IERR_C = FCVODE(CVODE_MEM, TEND, SUNVEC_Y, TCUR_C, CV_NORMAL)
         IF (IERR_C == CV_TOO_MUCH_WORK) THEN
            NTRY = NTRY +1
            CYCLE
         ELSE
            EXIT
         ENDIF
      ENDDO
   ENDIF

   IF (IERR_C .NE. CV_SUCCESS) THEN
      IF(IERR_C>=CVODE_ERR_CODE_MIN .AND. IERR_C<=CVODE_ERR_CODE_MAX) THEN
         CVODE_WARNING_CELLS(IERR_C) = CVODE_WARNING_CELLS(IERR_C) + 1
      ENDIF   
      IF (DEBUG) THEN
         IF (IERR_C == CV_TOO_MUCH_WORK) THEN
            WRITE(LU_ERR,'(A, 2E18.8, I8, A)')" WARN: CVODE took all internal substeps. CUR_CFD_TIME, DT, MAXTRY=", CUR_CFD_TIME, &
                        (TEND-TCUR), MAXTRY, ". If the warning persists, reduce the timestep."
         ELSE
            WRITE(LU_ERR,'(A, I4, A, 2E18.8, A)')" WARN: CVODE didn't finish ODE solution with message code:", IERR_C, &
                           " and CUR_CFD_TIME, DT=", CUR_CFD_TIME, (TEND-TCUR), ". If the warning persists, reduce the timestep."
         ENDIF

         CALL MOLAR_CONC_TO_MASS_FRAC(CC(1:N_TRACKED_SPECIES), ZZ(1:N_TRACKED_SPECIES))
         CALL CALC_EQUIV_RATIO(ZZ(1:N_TRACKED_SPECIES), EQUIV)
         DO NS = 1, N_TRACKED_SPECIES
            WRITE(LU_ERR,*)" ID, Y=",SPECIES_MIXTURE(NS)%ID, ZZ(NS)
         ENDDO 
         WRITE(LU_ERR,*)" EQUIVALENCE RATIO, TMP=", EQUIV,TMP_IN
         CALL CVODESTATS(CVODE_MEM) ! DIAGNOSTICS OUTPUT
      ENDIF   
   ENDIF   
ENDIF

CC = CVEC_C(1:N_TRACKED_SPECIES) !DISCARD THE TEMPERATURE.
TMP_OUT = CVEC_C(N_TRACKED_SPECIES+1)
IERR_C = FCVODEGETLASTSTEP(CVODE_MEM, CHEM_TIME_C(1))
CHEM_TIME=CHEM_TIME_C(1)

! CLEAN UP
DEALLOCATE(USER_DATA%ZZ_UNMIXED)
DEALLOCATE(USER_DATA%ZZ_CELL)
CALL FCVODEFREE(CVODE_MEM)
IERR_C = FSUNLINSOLFREE(SUNLINSOL_LS)
CALL FSUNMATDESTROY(SUNMAT_A)
CALL FN_VDESTROY(SUNVEC_Y)
CALL FN_VDESTROY(SUNATOL)
IERR_C = FSUNCONTEXT_FREE(SUNCTX)

IF (WRITE_SUBSTEPS) THEN
   TOTAL_SUBSTEPS_TAKEN = SUBSTEP_COUNT
   STOP_STATUS=CVODE_SUBSTEP_STOP
   RETURN
ENDIF


END SUBROUTINE CVODE_SERIAL


!> \brief CVODE error handler callback function, such that CVODE() doesn't output the error directly to stderr.
!> \param ERR_CODE The error code send by CVODE
!> \param MOD_NAME The module name where error occured send by CVODE
!> \param FUNC_NAME The functio name where error occured send by CVODE
!> \param MESSAGE The error message
!> \param USER_DATA User data, not used in FDS.
SUBROUTINE FDS_CVODE_ERR_HANDLER(LINE, FUNC_NAME, FILE_NAME, MESSAGE, ERR_CODE, USER_DATA, CTX) &
   BIND(C,NAME='FDS_CVODE_ERR_HANDLER')

INTEGER(C_INT),     VALUE :: LINE
CHARACTER(KIND=C_CHAR),DIMENSION(*),INTENT(IN):: FUNC_NAME
CHARACTER(KIND=C_CHAR),DIMENSION(*),INTENT(IN):: FILE_NAME
CHARACTER(KIND=C_CHAR),DIMENSION(*),INTENT(IN):: MESSAGE
INTEGER(C_INT),     VALUE :: ERR_CODE
TYPE(C_PTR),        VALUE :: USER_DATA
TYPE(C_PTR),        VALUE :: CTX       ! SUNCONTEXT POINTER

CHARACTER(LEN=200) :: TEMP_STRING
LOGICAL :: FOUND_NULL
INTEGER :: J

IF (DEBUG) THEN
   WRITE(LU_ERR,'(A, E18.8)')" WARN: CVODE message at CFD time. CUR_CFD_TIME=", CUR_CFD_TIME
   WRITE(LU_ERR,*) '  CVODE CODE   : ', ERR_CODE
   WRITE(LU_ERR,*) '  LINE NUMBER  : ', LINE

   ! Print Message
   FOUND_NULL = .FALSE.
   TEMP_STRING = ''
   J = 1
   DO WHILE (.NOT. FOUND_NULL)
       IF (MESSAGE(J) == C_NULL_CHAR) THEN
           FOUND_NULL = .TRUE.
       ELSE
           TEMP_STRING(J:J) = MESSAGE(J)
           J = J + 1
       END IF
   END DO
   WRITE(LU_ERR,*) 'CVODE MESSAGE : ', TRIM(TEMP_STRING)

   ! Print MOD_NAME
   FOUND_NULL = .FALSE.
   TEMP_STRING = ''
   J = 1
   DO WHILE (.NOT. FOUND_NULL)
       IF (FILE_NAME(J) == C_NULL_CHAR) THEN
           FOUND_NULL = .TRUE.
       ELSE
           TEMP_STRING(J:J) = FILE_NAME(J)
           J = J + 1
       END IF
   END DO
   WRITE(LU_ERR,*) '  FILE NAME       : ', TRIM(TEMP_STRING)

   ! Print func name
   FOUND_NULL = .FALSE.
   TEMP_STRING = ''
   J = 1
   DO WHILE (.NOT. FOUND_NULL)
       IF (FUNC_NAME(J) == C_NULL_CHAR) THEN
           FOUND_NULL = .TRUE.
       ELSE
           TEMP_STRING(J:J) = FUNC_NAME(J)
           J = J + 1
       END IF
   END DO
   WRITE(LU_ERR,*) '  FUNCTION     : ', TRIM(TEMP_STRING)

   IF (.NOT. C_ASSOCIATED(USER_DATA)) WRITE(LU_ERR,*)" NO USER_DATA IS PROVIDED"
   IF (.NOT. C_ASSOCIATED(CTX)) WRITE(LU_ERR,*)" SUNCONTEXT IS NOT VALID"
ENDIF

END SUBROUTINE FDS_CVODE_ERR_HANDLER



!> \brief print CVODE statistics from a CVODE memory object.
!> \param CVODE_MEM CVODE memory object.
SUBROUTINE CVODESTATS(CVODE_MEM)

!======= INCLUSIONS ===========
USE ISO_C_BINDING
USE FCVODE_MOD
USE GLOBAL_CONSTANTS

TYPE(C_PTR), INTENT(IN) :: CVODE_MEM ! SOLVER MEMORY STRUCTURE

INTEGER(C_INT)  :: IERR          ! ERROR FLAG

INTEGER(C_LONG) :: NSTEPS(1)     ! NUM STEPS
INTEGER(C_LONG) :: NFEVALS(1)    ! NUM FUNCTION EVALS
INTEGER(C_LONG) :: NLINSETUPS(1) ! NUM LINEAR SOLVER SETUPS
INTEGER(C_LONG) :: NETFAILS(1)   ! NUM ERROR TEST FAILS

INTEGER(C_INT)  :: QLAST(1)      ! METHOD ORDER IN LAST STEP
INTEGER(C_INT)  :: QCUR(1)       ! METHOD ORDER FOR NEXT STEP

REAL(C_DOUBLE)  :: HINUSED(1)    ! INITIAL STEP SIZE
REAL(C_DOUBLE)  :: HLAST(1)      ! LAST STEP SIZE
REAL(C_DOUBLE)  :: HCUR(1)       ! STEP SIZE FOR NEXT STEP
REAL(C_DOUBLE)  :: TCUR(1)       ! INTERNAL TIME REACHED

INTEGER(C_LONG) :: NNITERS(1)    ! NONLINEAR SOLVER ITERATIONS
INTEGER(C_LONG) :: NNCFAILS(1)   ! NONLINEAR SOLVER FAILS

INTEGER(C_LONG) :: NJEVALS(1)    ! NUM JACOBIAN EVALUATIONS

!======= INTERNALS ============

! GENERAL SOLVER STATISTICS
IERR = FCVODEGETINTEGRATORSTATS(CVODE_MEM, NSTEPS, NFEVALS, NLINSETUPS, &
    NETFAILS, QLAST, QCUR, HINUSED, HLAST, HCUR, TCUR)
IF (IERR /= 0) THEN
   WRITE(LU_ERR,*) 'ERROR IN FCVODEGETINTEGRATORSTATS, IERR = ', IERR, '; HALTING'
   STOP 1
END IF

! NONLINEAR SOLVER STATISTICS
IERR = FCVODEGETNONLINSOLVSTATS(CVODE_MEM, NNITERS, NNCFAILS)
IF (IERR /= 0) THEN
   WRITE(LU_ERR,*) 'ERROR IN FCVODEGETNONLINSOLVSTATS, IERR = ', IERR, '; HALTING'
   STOP 1
END IF

! NUMBER OF JACOBIAN EVALUATIONS
IERR = FCVODEGETNUMJACEVALS(CVODE_MEM, NJEVALS)
IF (IERR /= 0) THEN
   WRITE(LU_ERR,*) 'ERROR IN FCVODEGETNUMJACEVALS, IERR = ', IERR, '; HALTING'
   STOP 1
END IF

WRITE(LU_ERR,*) ' '
WRITE(LU_ERR,*) ' GENERAL SOLVER STATS:'
WRITE(LU_ERR,'(4X,A,I9)')    'TOTAL INTERNAL STEPS TAKEN =',NSTEPS
WRITE(LU_ERR,'(4X,A,I9)')    'TOTAL RHS FUNCTION CALLS   =',NFEVALS
WRITE(LU_ERR,'(4X,A,I9)')    'NUM LIN SOLVER SETUP CALLS =',NLINSETUPS
WRITE(LU_ERR,'(4X,A,I9)')    'NUM ERROR TEST FAILURES    =',NETFAILS
WRITE(LU_ERR,'(4X,A,I9)')    'LAST METHOD ORDER          =',QLAST
WRITE(LU_ERR,'(4X,A,I9)')    'NEXT METHOD ORDER          =',QCUR
WRITE(LU_ERR,'(4X,A,ES12.5)')'FIRST INTERNAL STEP SIZE   =',HINUSED
WRITE(LU_ERR,'(4X,A,ES12.5)')'LAST INTERNAL STEP SIZE    =',HLAST
WRITE(LU_ERR,'(4X,A,ES12.5)')'NEXT INTERNAL STEP SIZE    =',HCUR
WRITE(LU_ERR,'(4X,A,ES12.5)')'CURRENT INTERNAL TIME      =',TCUR
WRITE(LU_ERR,'(4X,A,I9)')    'NUM NONLINEAR SOLVER ITERS =',NNITERS
WRITE(LU_ERR,'(4X,A,I9)')    'NUM NONLINEAR SOLVER FAILS =',NNCFAILS
WRITE(LU_ERR,'(4X,A,I9)')    'NUM JACOBIAN EVALUATIONS   =',NJEVALS
WRITE(LU_ERR,*) ' '

RETURN

END SUBROUTINE CVODESTATS

END MODULE CVODE_INTERFACE

!-------------------------------------------------------------------------
!-------------------------------------------------------------------------
!***** Chemical Euilibrium calculation routines ******
!-------------------------------------------------------------------------
!-------------------------------------------------------------------------

MODULE CHEM_EQUIL

USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS   
USE TYPES
USE CHEMCONS
USE PROPERTY_DATA
USE, INTRINSIC :: ISO_C_BINDING
USE FSUNDIALS_CORE_MOD

IMPLICIT NONE

TYPE :: EQUILIBRIUM_OPTION
   INTEGER  :: OPTION                 ! 1-HP, 2-UV

   REAL(EB) :: FIXED_ENTH             ! J/KMOL
   REAL(EB) :: FIXED_PRES             ! PA
   REAL(EB) :: FIXED_INT_ENG          ! J/KMOL
   REAL(EB) :: FIXED_RHO              ! KG/M3

   REAL(EB) :: REL_ELEM_TOL   = 1.0E-8_EB    ! RELATIVE TOLERANCE
   REAL(EB) :: ABS_ELEM_TOL   = 1.0E-70_EB   ! ABSOLUTE TOL IN ELEMENT NUMBER
   INTEGER  :: MAX_ITERATIONS = 1000         ! MAXIMUM NUMBER OF ITERATIONS
   INTEGER  :: ELEM_SKIP = -1                ! ELEMENT TO SKIP because of SUM OF TARGET ELEMENT FRACTION =1
END TYPE EQUILIBRIUM_OPTION

LOGICAL :: DEBUG=.FALSE.

PUBLIC EQUILIBRATE

CONTAINS


!> \brief equilibrium routine
!> \param ZZ species mass fraction array
!> \param TMP_IN is the temperature
!> \param PRES_IN is the pressure
!> \param Option HP (default)-const enthalpy and pressure, UV-Constant volume and internal energy process.
SUBROUTINE EQUILIBRATE(ZZ, TMP_IN, PRES_IN, TMP_OUT, PRES_OUT,OPTION)
   USE PHYSICAL_FUNCTIONS, ONLY :GET_MOLECULAR_WEIGHT, MASS_FRAC_TO_MOLE_FRAC, GET_ENTHALPY,MOLE_FRAC_TO_MASS_FRAC

   REAL(EB), INTENT(INOUT) :: ZZ(N_TRACKED_SPECIES)
   REAL(EB), INTENT(IN) :: TMP_IN,PRES_IN
   REAL(EB), INTENT(OUT) :: TMP_OUT,PRES_OUT
   INTEGER, INTENT(IN) ::OPTION
   INTEGER  :: NE, NS, ELEM_INDX, MAX_NE_INDEX
   REAL(EB) :: TARGET_ELEM_MOL_FR(N_TRACKED_ELEMENTS), LAMBDA_RT(N_TRACKED_ELEMENTS+1)
   REAL(EB) :: XX(N_TRACKED_SPECIES)
   REAL(EB) :: MW, SUM_MOL_FR,TMP, PRES, MAX_ELEM_FRAC,VAL
   INTEGER :: IERR
   REAL(EB) :: ZZ_ORIG(N_TRACKED_SPECIES)

   TYPE(EQUILIBRIUM_OPTION) :: EQ_OPTION

   ZZ_ORIG = ZZ

   ! Calculate the mole fraction of species
   CALL MASS_FRAC_TO_MOLE_FRAC(ZZ, XX)
   
   ! Calculate element mole fraction (also target element mole fraction at equilibrium)
   TARGET_ELEM_MOL_FR = 0.0_EB
   SUM_MOL_FR =0._EB
   DO NE=1,N_TRACKED_ELEMENTS
      ELEM_INDX=TRACKED_ELEM_INDX(NE)
      DO NS=1,N_TRACKED_SPECIES
         IF (SPECIES_MIXTURE(NS)%ATOMS(ELEM_INDX) > 0) THEN ! ELEMENT PRESENT IN THE MOLECULE SYMBOL
            TARGET_ELEM_MOL_FR(NE) = TARGET_ELEM_MOL_FR(NE) + SPECIES_MIXTURE(NS)%ATOMS(ELEM_INDX)*XX(NS)
         ENDIF
      ENDDO 
      SUM_MOL_FR = SUM_MOL_FR +TARGET_ELEM_MOL_FR(NE)  
   ENDDO

   MAX_ELEM_FRAC=-1000._EB
   DO NE=1,N_TRACKED_ELEMENTS
      TARGET_ELEM_MOL_FR(NE) = TARGET_ELEM_MOL_FR(NE)/SUM_MOL_FR
      IF (TARGET_ELEM_MOL_FR(NE) > MAX_ELEM_FRAC) THEN
         MAX_NE_INDEX = NE
         MAX_ELEM_FRAC = TARGET_ELEM_MOL_FR(NE)
      ENDIF
   ENDDO

   ! Store the fixed values of equilibrium calculation. Currently HP and UV is used. 
   ! If needed other options will be used in the future.
   EQ_OPTION%ELEM_SKIP=MAX_NE_INDEX
   CALL GET_MOLECULAR_WEIGHT(ZZ,MW)
   IF (OPTION .EQ. 1) THEN ! FIXED HP
      EQ_OPTION%OPTION=1
      CALL GET_ENTHALPY(ZZ,EQ_OPTION%FIXED_ENTH,TMP_IN) ! J/kg
      EQ_OPTION%FIXED_PRES = PRES_IN
   ELSE ! FIXED UV
      EQ_OPTION%OPTION=2
      EQ_OPTION%FIXED_RHO = PRES_IN*MW/R0/TMP_IN ! [PR]= Pa, [MW] = kg/kmol, [R0]= J/K/kmol, [TMP]=K, [RHO]= kg/m3
      CALL GET_ENTHALPY(ZZ,EQ_OPTION%FIXED_ENTH,TMP_IN)
      EQ_OPTION%FIXED_INT_ENG = EQ_OPTION%FIXED_ENTH - R0*TMP_IN/MW ! J/kg
   ENDIF

   ! Calculate an approximate solution based on Stoichiometric matrix
   TMP = TMP_IN 
   PRES = PRES_IN
   CALL SET_APPROXIMATE_INITIAL_MOLES_SOLUTION(XX,TMP,PRES,TMP_OUT,PRES_OUT,EQ_OPTION)

   ! get an estimate element potentials (important to get an good initial lambda_rt).  
   ! To get a even better estimate of element potentials we can use Brinkley solution. Need to check if it is needed.
   CALL GET_ELEMENT_POTENTIAL(XX,TMP_OUT,PRES_OUT,TARGET_ELEM_MOL_FR,LAMBDA_RT(1:N_TRACKED_ELEMENTS))

   ! Iterate to solve equlibrium based on fixed values (core of element potential)
   CALL SOLVE_EQUILIBRIUM(XX,TMP_OUT, PRES_OUT,TARGET_ELEM_MOL_FR,LAMBDA_RT,EQ_OPTION,IERR)
   CALL MOLE_FRAC_TO_MASS_FRAC(XX,ZZ) ! Lets ignore warning and take the last value.
   IF(IERR >0) THEN
      EQUIL_WARNING_CELLS = EQUIL_WARNING_CELLS+1
      WRITE(LU_ERR,'(A)') '------Failed in SOLVE_EQUILIBRIUM.----'
      WRITE(LU_ERR,*)"RANK,TMP,PRES:",MY_RANK,TMP_IN, PRES_IN
      DO NS = 1,N_TRACKED_SPECIES
         WRITE(LU_ERR,'(I4,A40,A,ES18.6)')MY_RANK,TRIM(SPECIES_MIXTURE(NS)%ID),":",ZZ_ORIG(NS)
      ENDDO
      RETURN
   ENDIF


   
   WRITE(LU_ERR,*) "End EQUILIBRATE: TMP_IN, PRES_IN,TMP_OUT,PRES_OUT=",TMP_IN, PRES_IN,TMP_OUT,PRES_OUT
   DO NS = 1, N_TRACKED_SPECIES
      IF (ZZ(NS) >1.e-4_EB) WRITE(LU_ERR,'(A,A20, F15.6)') "End EQUILIBRATE: ID,ZZ=",SPECIES_MIXTURE(NS)%ID,ZZ(NS)
   ENDDO
   CALL GET_ENTHALPY(ZZ,VAL,TMP_OUT)
   WRITE(LU_ERR,*)"FIXED_ENTH, ENTH_EQUIL=",EQ_OPTION%FIXED_ENTH,VAL
   
END SUBROUTINE EQUILIBRATE

SUBROUTINE SOLVE_EQUILIBRIUM(XX,TMP,PRES,TARGET_ELEM_MOL_FR,LAMBDA_RT,EQ_OPTION, IERR)
   USE MATH_FUNCTIONS, ONLY : LINEAR_SYSTEM_SOLVE
   !------------------------------------------------------------
   ! ARGUMENTS
   !------------------------------------------------------------
   REAL(EB), INTENT(INOUT) :: XX(N_TRACKED_SPECIES)                 ! SPECIES MOLE FRACTIONS
   REAL(EB), INTENT(INOUT) :: TMP                                   ! TEMPERATURE
   REAL(EB), INTENT(INOUT) :: PRES                                  ! PRESSURE
   REAL(EB), INTENT(IN)    :: TARGET_ELEM_MOL_FR(N_TRACKED_ELEMENTS)! TARGET ELEMENT MOLES
   REAL(EB), INTENT(INOUT) :: LAMBDA_RT(N_TRACKED_ELEMENTS+1)       ! ELEMENT POTENTIALS (+1 for log(T))
   TYPE(EQUILIBRIUM_OPTION), INTENT(IN) :: EQ_OPTION                ! OPTIONS FOR EQUILIBRATION
   INTEGER, INTENT (OUT) :: IERR


   !------------------------------------------------------------
   ! LOCAL VARIABLES
   !------------------------------------------------------------
   INTEGER :: NE, ITER, NVAR, FAIL
   REAL(EB) :: F, OLD_F, DELTAX, DELTAY, FCTR, TOL_VAL,MIN_ALLOWED_TMP,MAX_ALLOWED_TMP
   LOGICAL :: PASS_THIS
   REAL(EB), PARAMETER:: ELEM_FRAC_CUTOFF=1.E-100_EB

   ! STATIC ARRAYS
   REAL(EB) :: RES_TRIAL(N_TRACKED_ELEMENTS+1),RES_TRIAL_NEW(N_TRACKED_ELEMENTS+1)
   REAL(EB) :: JAC(N_TRACKED_ELEMENTS+1, N_TRACKED_ELEMENTS+1)
   REAL(EB) :: ABOVE(N_TRACKED_ELEMENTS+1)
   REAL(EB) :: BELOW(N_TRACKED_ELEMENTS+1)
   REAL(EB) :: OLDX(N_TRACKED_ELEMENTS+1)
   REAL(EB) :: GRAD(N_TRACKED_ELEMENTS+1)

   REAL(EB) :: FIXED_1ST_VAL,FIXED_2ND_VAL,XVAL,YVAL, NEW_VAL
   !CHARACTER(MESSAGE_LENGTH) :: MESSAGE


   NVAR = N_TRACKED_ELEMENTS + 1
   GRAD = 0.0_EB
   OLDX = 0.0_EB
   RES_TRIAL = 0.0_EB
   FAIL = 0

   ! INSTALL LOG(TEMPERATURE) INTO LAST SLOT
   LAMBDA_RT(N_TRACKED_ELEMENTS+1) = LOG(TMP)

   ! SET BOUNDS FOR ELEMENTS
   DO NE = 1, N_TRACKED_ELEMENTS
     ABOVE(NE) = 200.0_EB
     BELOW(NE) = -2000.0_EB
     IF (TARGET_ELEM_MOL_FR(NE) < ELEM_FRAC_CUTOFF) THEN
         LAMBDA_RT(NE) = -1000.0_EB
     END IF
   END DO

   ! TEMPERATURE BOUNDS
   MIN_ALLOWED_TMP=300.0_EB
   MAX_ALLOWED_TMP=5000.0_EB !REAL(I_MAX_TEMP)
   ABOVE(N_TRACKED_ELEMENTS+1) = LOG(MAX_ALLOWED_TMP + 25.0_EB)
   BELOW(N_TRACKED_ELEMENTS+1) = LOG(MIN_ALLOWED_TMP - 25.0_EB)

   CALL GET_FIRST_FIXED_VAL(EQ_OPTION,FIXED_1ST_VAL)
   CALL GET_SECOND_FIXED_VAL(EQ_OPTION,FIXED_2ND_VAL)

   !------------------------------------------------------------
   ! NEWTON-RAPHSON ITERATION
   !------------------------------------------------------------
   DO ITER = 1, EQ_OPTION%MAX_ITERATIONS

      ! CALCULATE RESIDUAL
      CALL EQUIL_RESIDUAL(XX, PRES, LAMBDA_RT, TARGET_ELEM_MOL_FR, RES_TRIAL, EQ_OPTION)
      F = 0.5_EB * DOT_PRODUCT(RES_TRIAL, RES_TRIAL)

      ! CHECK EXTRA CONSTRAINTS
      CALL GET_FIRST_VAR_VAL(XX,TMP,PRES,EQ_OPTION,XVAL)
      CALL GET_SECOND_VAR_VAL(XX,TMP,PRES,EQ_OPTION,YVAL)
      DELTAX = (XVAL - FIXED_1ST_VAL)/FIXED_1ST_VAL
      DELTAY = (YVAL - FIXED_2ND_VAL)/FIXED_2ND_VAL

      ! CHECK ELEMENT CONVERGENCE
      PASS_THIS = .TRUE.
      DO NE = 1, N_TRACKED_ELEMENTS
         TOL_VAL = TARGET_ELEM_MOL_FR(NE)*EQ_OPTION%REL_ELEM_TOL + EQ_OPTION%ABS_ELEM_TOL
         IF (ABS(RES_TRIAL(NE)) > TOL_VAL) PASS_THIS = .FALSE.
      END DO

      ! CHECK OVERALL CONVERGENCE
      TMP = EXP(LAMBDA_RT(N_TRACKED_ELEMENTS+1))
      IF (ITER > 1 .AND. PASS_THIS .AND. ABS(DELTAX) < EQ_OPTION%REL_ELEM_TOL .AND. &
         ABS(DELTAY) < EQ_OPTION%REL_ELEM_TOL) THEN
         EXIT
      END IF

      ! CALCULATE JACOBIAN
      CALL EQUIL_JACOBIAN(LAMBDA_RT, TARGET_ELEM_MOL_FR, JAC, EQ_OPTION)

      ! SAVE OLD VALUES
      OLDX = LAMBDA_RT
      OLD_F = F

      ! NEGATE RESIDUALS FOR SOLVER
      RES_TRIAL = -RES_TRIAL

      ! SOLVE LINEAR SYSTEM: JAC * STEP = -RES_TRIAL
      CALL LINEAR_SYSTEM_SOLVE(NVAR,NVAR,JAC, RES_TRIAL,RES_TRIAL_NEW,IERR)
      IF(IERR >0) THEN
         !WRITE(MESSAGE,'(A)') 'Singular matrix to solve element residuals.'
         !IF (MY_RANK==0) WRITE(LU_ERR,'(A)') TRIM(MESSAGE)
         RETURN
      ENDIF

      ! BOUNDS AND DAMPING
      FCTR = 1.0_EB
      DO NE = 1, NVAR
         NEW_VAL = LAMBDA_RT(NE)+RES_TRIAL_NEW(NE)
         IF (NEW_VAL > ABOVE(NE)) THEN
            FCTR = MIN(FCTR, 0.8_EB*(ABOVE(NE)-LAMBDA_RT(NE))/(NEW_VAL-LAMBDA_RT(NE)))
         ELSEIF (NEW_VAL < BELOW(NE)) THEN
            ! Check if this index belongs to an element potential
            IF (NE <= N_TRACKED_ELEMENTS .AND. NE .NE. EQ_OPTION%ELEM_SKIP) THEN
               RES_TRIAL_NEW(NE) = -50.0_EB
               IF (LAMBDA_RT(NE) < (BELOW(NE) + 50.0_EB)) THEN
                  RES_TRIAL_NEW(NE) = BELOW(NE) - LAMBDA_RT(NE)
               END IF

            ELSE
              ! For non-element variables (like T or P), scale the step factor
              FCTR = MIN(FCTR, 0.8_EB * (LAMBDA_RT(NE) - BELOW(NE)) / (LAMBDA_RT(NE)-NEW_VAL))
            ENDIF
         ENDIF   

         IF (NE == NVAR .AND. ABS(RES_TRIAL_NEW(NE)) > 0.2) THEN 
             FCTR = MIN(FCTR, 0.2/ABS(RES_TRIAL_NEW(NE)))
         ENDIF
      END DO

      RES_TRIAL = RES_TRIAL_NEW * FCTR

      ! DAMPING STEP
      IF (.NOT. DAMPSTEP(OLDX, RES_TRIAL, LAMBDA_RT)) THEN
         FAIL = FAIL + 1
         IF (FAIL > 3) THEN
             PRINT *, "Cannot find acceptable Newton damping factor"
             EXIT
         END IF
      ELSE
         FAIL = 0
      END IF

   END DO
END SUBROUTINE SOLVE_EQUILIBRIUM


LOGICAL FUNCTION DAMPSTEP(OLDX, STEP, X)
   REAL(EB), INTENT(IN)    :: OLDX(N_TRACKED_ELEMENTS+1)
   REAL(EB), INTENT(IN)    :: STEP(N_TRACKED_ELEMENTS+1)
   REAL(EB), INTENT(INOUT) :: X(N_TRACKED_ELEMENTS+1)

   INTEGER  :: NE
   REAL(EB) :: DAMP

   DAMP = 1.0_EB
   DAMPSTEP = .TRUE.

   !------------------------------------------------------------
   ! DELTA DAMPING ON ELEMENT POTENTIALS
   !------------------------------------------------------------
   DO NE = 1, N_TRACKED_ELEMENTS
         IF (STEP(NE) >  0.75_EB) DAMP = MIN(DAMP,  0.75_EB / STEP(NE))
         IF (STEP(NE) < -0.75_EB) DAMP = MIN(DAMP, -0.75_EB / STEP(NE))
   END DO

   !------------------------------------------------------------
   ! UPDATE SOLUTION VECTOR
   !------------------------------------------------------------
   X = OLDX + DAMP * STEP

   !------------------------------------------------------------
   ! LOGGING
   !------------------------------------------------------------
   IF (DEBUG) THEN
     WRITE(LU_ERR,'(A,ES12.5)') 'SOLUTION UNKNOWNS: DAMP = ', DAMP
     WRITE(LU_ERR,'(A)') '            X_NEW        X_OLD        STEP'
     DO NE = 1, N_TRACKED_ELEMENTS
         WRITE(LU_ERR,'(3ES14.5)') X(NE), OLDX(NE), STEP(NE)
     END DO
   END IF

END FUNCTION DAMPSTEP



SUBROUTINE EQUIL_RESIDUAL(XX, PRES, LAMBDA_RT, TARGET_ELEM_MOL_FR, RESIDUAL, EQ_OPTION)

    !------------------------------------------------------------
    ! ARGUMENTS
    !------------------------------------------------------------
    REAL(EB), INTENT(OUT)  :: XX(N_TRACKED_SPECIES)                      ! MOLE FRACTIONS (NS)
    REAL(EB), INTENT(OUT)  :: PRES                                       ! PRESSURE
    REAL(EB), INTENT(IN)  :: LAMBDA_RT(N_TRACKED_ELEMENTS+1)            ! ELEMENT POTENTIALS (NE)
    REAL(EB), INTENT(IN)  :: TARGET_ELEM_MOL_FR(N_TRACKED_ELEMENTS)     ! ELEMENT MOLE FRACTIONS
    REAL(EB), INTENT(OUT) :: RESIDUAL(N_TRACKED_ELEMENTS+1)             ! ELEMENTS, FIXED VAR1, FIXED VAR2
    TYPE(EQUILIBRIUM_OPTION), INTENT(IN) :: EQ_OPTION

    !------------------------------------------------------------
    ! LOCALS
    !------------------------------------------------------------
    INTEGER :: NE, NS,ELEM_INDX
    REAL(EB) :: XVAL, YVAL, TMP 
    REAL(EB) :: XX_VAL, YY_VAL,SUM_MOL_FR
    REAL(EB) :: CURRENT_ELEM_MOL_FR(N_TRACKED_ELEMENTS)
    REAL(EB), PARAMETER :: ELEM_FRAC_CUTOFF =1.E-100_EB

    !------------------------------------------------------------
    ! GET CONSTRAINT VALUES
    !------------------------------------------------------------
    CALL GET_FIRST_FIXED_VAL(EQ_OPTION,XVAL)
    CALL GET_SECOND_FIXED_VAL(EQ_OPTION,YVAL)

    !------------------------------------------------------------
    ! SET EQUILIBRIUM STATE (THERMO FROM XX, T, P)
    !------------------------------------------------------------
    !CALL SET_EQUIL_STATE(XX, EXP(LAMBDA_RT(N_TRACKED_ELEMENTS)), PRES, LAMBDA_RT)
    
    CALL SET_EQUIL_STATE(XX, PRES, LAMBDA_RT)

   ! Calculate element mole fraction
   CURRENT_ELEM_MOL_FR = 0.0_EB
   SUM_MOL_FR = 0._EB
   DO NE=1,N_TRACKED_ELEMENTS
      ELEM_INDX=TRACKED_ELEM_INDX(NE)
      DO NS=1,N_TRACKED_SPECIES
         IF (SPECIES_MIXTURE(NS)%ATOMS(ELEM_INDX) > 0) THEN ! ELEMENT PRESENT IN THE MOLECULE SYMBOL
            CURRENT_ELEM_MOL_FR(NE) = CURRENT_ELEM_MOL_FR(NE) + SPECIES_MIXTURE(NS)%ATOMS(ELEM_INDX)*XX(NS)
         ENDIF
      ENDDO 
      SUM_MOL_FR = SUM_MOL_FR +CURRENT_ELEM_MOL_FR(NE)  
   ENDDO

   DO NE=1,N_TRACKED_ELEMENTS
      CURRENT_ELEM_MOL_FR(NE) = CURRENT_ELEM_MOL_FR(NE)/SUM_MOL_FR
   ENDDO


   !------------------------------------------------------------
   ! ELEMENT RESIDUALS (LOOP OVER ELEMENTS)
   !------------------------------------------------------------
   DO NE = 1, N_TRACKED_ELEMENTS
     IF (TARGET_ELEM_MOL_FR(NE) < ELEM_FRAC_CUTOFF) THEN
         RESIDUAL(NE) = LAMBDA_RT(NE) + 1000.0_EB
     ELSEIF (NE > N_TRACKED_ELEMENTS) THEN
         RESIDUAL(NE) = LAMBDA_RT(NE)
     ELSE
         ! SMALL-NUMBER PROTECTION (L'HÔPITAL)
         IF (TARGET_ELEM_MOL_FR(NE)  < 1.0E-10_EB .OR. &
             CURRENT_ELEM_MOL_FR(NE) < 1.0E-10_EB ) THEN
             RESIDUAL(NE) = TARGET_ELEM_MOL_FR(NE) - CURRENT_ELEM_MOL_FR(NE)
         ELSE
             RESIDUAL(NE) = LOG( (1.0_EB + TARGET_ELEM_MOL_FR(NE)) / &
                                      (1.0_EB + CURRENT_ELEM_MOL_FR(NE)) )
         ENDIF
     ENDIF

   ENDDO

   !------------------------------------------------------------
   ! EXTRA CONSTRAINTS
   !------------------------------------------------------------
   TMP = EXP(LAMBDA_RT(N_TRACKED_ELEMENTS+1))
   CALL GET_FIRST_VAR_VAL(XX,TMP,PRES,EQ_OPTION,XX_VAL) 
   CALL GET_SECOND_VAR_VAL(XX,TMP,PRES,EQ_OPTION,YY_VAL)

   RESIDUAL(N_TRACKED_ELEMENTS+1) = XX_VAL / XVAL - 1.0_EB
   RESIDUAL(EQ_OPTION%ELEM_SKIP) = YY_VAL / YVAL - 1.0_EB

END SUBROUTINE EQUIL_RESIDUAL

SUBROUTINE SET_EQUIL_STATE(XX,PRES,LAMBDA_RT)
   USE PHYSICAL_FUNCTIONS, ONLY : GET_GIBBS_ENERGY_Z_INTERP

   REAL(EB), INTENT(OUT) :: XX(N_TRACKED_SPECIES)           ! MOLE FRACTIONS
   REAL(EB), INTENT(OUT) :: PRES                            ! PRESSURE
   REAL(EB), INTENT(IN)  :: LAMBDA_RT(N_TRACKED_ELEMENTS+1) ! ELEMENT POTENTIALS


   INTEGER  :: NS, NE
   REAL(EB) :: MU_RT(N_TRACKED_SPECIES),GRT(N_TRACKED_SPECIES),PARTIAL_PRES(N_TRACKED_SPECIES)
   REAL(EB) :: TMP,DUMMY,DUMMY2,PRES_OLD

   TMP = EXP(LAMBDA_RT(N_TRACKED_ELEMENTS+1))
   MU_RT = 0.0_EB
   DO NS = 1, N_TRACKED_SPECIES
     DO NE = 1, N_TRACKED_ELEMENTS
         MU_RT(NS) = MU_RT(NS) + LAMBDA_RT(NE) * &
               SPECIES_MIXTURE(NS)%ATOMS(TRACKED_ELEM_INDX(NE))
     END DO
   END DO

   DO NS = 1, N_TRACKED_SPECIES
      CALL GET_GIBBS_ENERGY_Z_INTERP(NS,GRT(NS),TMP,P_STP)
      GRT(NS)=GRT(NS)/R0/TMP
   ENDDO   

   !------------------------------------------------------------
   ! COMPUTE SPECIES PARTIAL PRESSURES
   !------------------------------------------------------------

   PARTIAL_PRES = 0.0_EB
   PRES_OLD = PRES
   PRES = 0.0_EB
   DO NS = 1, N_TRACKED_SPECIES
      DUMMY = -GRT(NS) + MU_RT(NS)
      IF (DUMMY < -600.0_EB) THEN
         PARTIAL_PRES(NS) = 0.0_EB
      ELSEIF (DUMMY > 300.0_EB) THEN
         DUMMY2 = DUMMY / 300.0_EB
         DUMMY2 = DUMMY2*DUMMY2
         PARTIAL_PRES(NS) = P_STP * EXP(300.0_EB) * DUMMY2
      ELSE
         PARTIAL_PRES(NS) = P_STP * EXP(DUMMY)
      ENDIF
      PRES = PRES + PARTIAL_PRES(NS)
   END DO

   
   !------------------------------------------------------------
   ! SET MOLE FRACTIONS
   !------------------------------------------------------------
   IF (PRES > 0.0_EB) THEN
      DO NS = 1, N_TRACKED_SPECIES
         XX(NS) = PARTIAL_PRES(NS) / PRES
      ENDDO
   ELSE 
      XX = 0.0_EB
   ENDIF 

END SUBROUTINE SET_EQUIL_STATE


SUBROUTINE EQUIL_JACOBIAN(LAMBDA_RT, TARGET_ELEM_MOL_FR, JAC, EQ_OPTION)
   REAL(EB), INTENT(INOUT)    :: LAMBDA_RT(N_TRACKED_ELEMENTS+1)             ! ITERATION VARIABLES
   REAL(EB), INTENT(IN)    :: TARGET_ELEM_MOL_FR(:)
   REAL(EB), INTENT(OUT)   :: JAC(N_TRACKED_ELEMENTS+1,N_TRACKED_ELEMENTS+1)  ! JACOBIAN MATRIX
   TYPE(EQUILIBRIUM_OPTION), INTENT(IN) :: EQ_OPTION

   !------------------------------------------------------------
   ! LOCALS
   !------------------------------------------------------------
   INTEGER :: NE, NS
   INTEGER :: NVAR
   REAL(EB) :: ATOL
   REAL(EB) :: XX(N_TRACKED_SPECIES),XSAVE, DX, RDX, PRES
   REAL(EB) :: R0(N_TRACKED_ELEMENTS+1), R1(N_TRACKED_ELEMENTS+1)

   !------------------------------------------------------------
   ! INITIALIZATION
   !------------------------------------------------------------
   NVAR = N_TRACKED_ELEMENTS+1
   ATOL = 1.0E-10_EB

   !------------------------------------------------------------
   ! BASE RESIDUAL
   !------------------------------------------------------------
   !CALL EQUIL_RESIDUAL(XX, PRES, LAMBDA_RT, TARGET_ELEM_MOL_FR, R0, EQ_OPTION)

   !------------------------------------------------------------
   ! FINITE-DIFFERENCE JACOBIAN
   !------------------------------------------------------------
   DO NS = 1, NVAR

     XSAVE = LAMBDA_RT(NS)
     DX = MAX(ATOL, ABS(XSAVE) * 1.0E-8_EB)

     LAMBDA_RT(NS) = XSAVE + DX
     CALL EQUIL_RESIDUAL(XX, PRES, LAMBDA_RT, TARGET_ELEM_MOL_FR, R1, EQ_OPTION)

     LAMBDA_RT(NS) = XSAVE - DX
     CALL EQUIL_RESIDUAL(XX, PRES, LAMBDA_RT, TARGET_ELEM_MOL_FR, R0, EQ_OPTION)

     RDX = 0.5_EB / DX

     ! JACOBIAN COLUMN
     DO NE = 1, NVAR
         JAC(NE, NS) = (R1(NE) - R0(NE)) * RDX
     END DO

     ! RESTORE VARIABLE
     LAMBDA_RT(NS) = XSAVE

   END DO


END SUBROUTINE EQUIL_JACOBIAN


SUBROUTINE GET_ELEMENT_POTENTIAL(XX, TMP, PRES, TARGET_ELEM_MOL_FR, LAMBDA_RT)
   USE PHYSICAL_FUNCTIONS, ONLY : GET_GIBBS_ENERGY_Z_INTERP
   USE MATH_FUNCTIONS, ONLY : LINEAR_SYSTEM_SOLVE

   ! Arguments
   !-----------------------------
   REAL(EB), INTENT(INOUT) :: XX(N_TRACKED_SPECIES)     ! species mole fractions
   REAL(EB), INTENT(IN)    :: TMP, PRES
   REAL(EB), INTENT(IN)    :: TARGET_ELEM_MOL_FR(N_TRACKED_ELEMENTS)
   REAL(EB), INTENT(OUT)   :: LAMBDA_RT(N_TRACKED_ELEMENTS)


   !-----------------------------
   ! Local variables
   !-----------------------------
   INTEGER :: N_COMPONENTS
   INTEGER :: NS, NE
   INTEGER  :: SPECIES_ORDER(N_TRACKED_SPECIES)
   INTEGER  :: ELEMENTS_ORDER(N_TRACKED_ELEMENTS)
   REAL(EB) :: LAMBDA_RT_DUMMY(N_TRACKED_ELEMENTS)

   CHARACTER(MESSAGE_LENGTH) :: MESSAGE

   INTEGER :: IERR
   INTEGER, ALLOCATABLE :: IPIV(:)
   REAL(EB), ALLOCATABLE :: A(:,:), B(:),MU_RT(:)

   !-----------------------------
   ! Calculate basis
   !-----------------------------
   CALL BASISOPTIMIZE(XX, SPECIES_ORDER, ELEMENTS_ORDER, N_COMPONENTS)

   
   !-----------------------------
   ! Rearrange elements
   !-----------------------------
   CALL ELEMREARRANGE(N_COMPONENTS, TARGET_ELEM_MOL_FR, SPECIES_ORDER, ELEMENTS_ORDER)

   
   !---------------------------------------------------------
   ! Solve for element potentials:
   ! Solve linear system.
   ! A * x = b
   !---------------------------------------------------------

   ALLOCATE(A(N_COMPONENTS, N_COMPONENTS), &
            B(N_COMPONENTS), &
            IPIV(N_COMPONENTS), &
            MU_RT(N_COMPONENTS))

   DO NS = 1, N_COMPONENTS
      DO NE = 1, N_COMPONENTS
         A(NS, NE) = SPECIES_MIXTURE(SPECIES_ORDER(NS))%ATOMS(TRACKED_ELEM_INDX(ELEMENTS_ORDER(NE)))
      END DO
   END DO

   DO NS = 1, N_COMPONENTS
      CALL GET_GIBBS_ENERGY_Z_INTERP(SPECIES_ORDER(NS), MU_RT(NS), TMP, PRES)
      MU_RT(NS) = MU_RT(NS)+LOG(XX(SPECIES_ORDER(NS))+TWO_EPSILON_EB)
      MU_RT(NS) = MU_RT(NS)/ (R0 * TMP)
      B(NS) = MU_RT(NS)
   END DO

   CALL LINEAR_SYSTEM_SOLVE(N_COMPONENTS,N_COMPONENTS,A,B,LAMBDA_RT_DUMMY,IERR)

   IF(IERR >0) THEN
      WRITE(MESSAGE,'(A,A,A)') 'Singular matrix to solve element potential.'
      IF (MY_RANK==0) WRITE(LU_ERR,'(A)') TRIM(MESSAGE)
      RETURN
   ENDIF

   DO NE = N_COMPONENTS + 1, N_TRACKED_ELEMENTS
      LAMBDA_RT_DUMMY(ELEMENTS_ORDER(NE) ) = 0.0_EB
   END DO

   DO NE = 1, N_TRACKED_ELEMENTS    
        LAMBDA_RT(ELEMENTS_ORDER(NE))=LAMBDA_RT_DUMMY(NE) 
     ENDDO 

   DEALLOCATE(A, B, IPIV, MU_RT)
END SUBROUTINE GET_ELEMENT_POTENTIAL



SUBROUTINE BASISOPTIMIZE(XX,SPECIES_ORDER,ELEMENTS_ORDER,N_COMPONENT)

   ! -------------------------
   ! Inputs
   REAL(EB), INTENT(IN) :: XX(N_TRACKED_SPECIES)

   ! Outputs
   INTEGER, INTENT(OUT) :: SPECIES_ORDER(N_TRACKED_SPECIES)
   INTEGER, INTENT(OUT) :: ELEMENTS_ORDER(N_TRACKED_ELEMENTS)
   INTEGER, INTENT(OUT) :: N_COMPONENT

   ! -------------------------
   ! Local variables
   INTEGER :: NS, NE, I, J, KK, JR
   REAL(EB) :: MOLNUM(N_TRACKED_SPECIES)
   REAL(EB) :: SM(N_TRACKED_ELEMENTS, N_TRACKED_ELEMENTS)
   REAL(EB) :: SA(N_TRACKED_ELEMENTS)
   REAL(EB) :: SS(N_TRACKED_ELEMENTS)
   REAL(EB) :: XMAX
   INTEGER :: DUMMY_INT

   REAL(EB), PARAMETER :: USED_BEFORE = -1.0E300_EB
   REAL(EB), PARAMETER :: TOL = 1.0E-6_EB

   ! -------------------------
   ! Initialization
   DO NS = 1, N_TRACKED_SPECIES
      SPECIES_ORDER(NS) = NS
      MOLNUM(NS) = XX(NS)
   END DO

   DO NE = 1, N_TRACKED_ELEMENTS
      ELEMENTS_ORDER(NE) = NE
      SA(NE) = 0.0_EB
   END DO

   SM = 0.0_EB
   SS = 0.0_EB

   ! Maximum possible number of components
   N_COMPONENT = MIN(N_TRACKED_SPECIES, N_TRACKED_ELEMENTS)
   
   JR = 0

   ! =============================
   ! Main component selection loop
   ! =============================
   DO WHILE (JR < N_COMPONENT)

      ! ----------------------------------
      ! Pick species with max mole number
      ! ----------------------------------
      XMAX = -1.0_EB
      KK = -1
      DO NS = 1, N_TRACKED_SPECIES
         IF (MOLNUM(NS) > XMAX) THEN
            XMAX = MOLNUM(NS)
            KK = NS
         END IF
      END DO

      IF (KK < 0) EXIT
      IF (MOLNUM(KK) == USED_BEFORE) EXIT

      ! Mark as used
      MOLNUM(KK) = USED_BEFORE

      ! ----------------------------------
      ! Build formula vector for species KK
      ! ----------------------------------
      DO NE = 1, N_TRACKED_ELEMENTS
         SM(NE, JR+1) = SPECIES_MIXTURE(KK)%ATOMS(TRACKED_ELEM_INDX(ELEMENTS_ORDER(NE)))
      END DO

      ! ----------------------------------
      ! Modified Gram-Schmidt
      ! ----------------------------------
      IF (JR > 0) THEN
         DO J = 1, JR
            SS(J) = 0.0_EB
            DO NE = 1, N_TRACKED_ELEMENTS
               SS(J) = SS(J) + SM(NE, JR+1) * SM(NE, J)
            END DO
            SS(J) = SS(J) / SA(J)
            
            DO NE = 1, N_TRACKED_ELEMENTS
               SM(NE, JR+1) = SM(NE, JR+1) - SS(J) * SM(NE, J)
            END DO
         END DO
      END IF

      ! ----------------------------------
      ! Compute norm
      ! ----------------------------------
      SA(JR+1) = 0.0_EB
      DO NE = 1, N_TRACKED_ELEMENTS
         SA(JR+1) = SA(JR+1) + SM(NE, JR+1)**2
      END DO

      ! ----------------------------------
      ! Accept or reject
      ! ----------------------------------
      IF (SA(JR+1) > TOL) THEN
         JR = JR + 1
         ! Move accepted species to front
         IF (SPECIES_ORDER(JR) /= KK) THEN
            DO I = JR, N_TRACKED_SPECIES
               IF (SPECIES_ORDER(I) == KK) THEN
                  DUMMY_INT = SPECIES_ORDER(JR)
                  SPECIES_ORDER(JR) = KK
                  SPECIES_ORDER(I) = DUMMY_INT
                  EXIT
               END IF
            END DO
         END IF
      END IF

   END DO

   N_COMPONENT = JR

END SUBROUTINE BASISOPTIMIZE


SUBROUTINE ELEMREARRANGE(N_COMPONENTS, TARGET_ELEM_MOL_FR, SPECIES_ORDER, ELEMENTS_ORDER)

   INTEGER, INTENT(IN) :: N_COMPONENTS
   REAL(EB), INTENT(IN) :: TARGET_ELEM_MOL_FR(N_TRACKED_ELEMENTS)
   INTEGER, INTENT(IN) :: SPECIES_ORDER(N_TRACKED_SPECIES)
   INTEGER, INTENT(INOUT) :: ELEMENTS_ORDER(N_TRACKED_ELEMENTS)

   ! Local variables
   INTEGER :: NS, NE, JR, JL, K, KK, ML
   INTEGER :: DUMMY_INT
   REAL(EB) :: EABUND(N_TRACKED_ELEMENTS)
   REAL(EB) :: SA(N_TRACKED_ELEMENTS)
   REAL(EB) :: SS(N_TRACKED_ELEMENTS)
   REAL(EB) :: SM(N_TRACKED_ELEMENTS, N_TRACKED_ELEMENTS)
   REAL(EB), PARAMETER :: TOL = 1.0D-6
   REAL(EB), PARAMETER :: USEDBEFORE = -1.0D100

   DO NE = 1, N_TRACKED_ELEMENTS
     IF (ELEMENTS_ORDER(NE) <= 0) ELEMENTS_ORDER(NE) = NE
     SA(NE) = 0.0_EB
   END DO

   ! Compute element abundances based on species mixture
   DO NE = 1, N_TRACKED_ELEMENTS
     EABUND(NE) = TARGET_ELEM_MOL_FR(NE)
   END DO

   ! Find independent elements
   JR = 0
   DO WHILE (JR < N_COMPONENTS)
     ! Find next candidate element
     K = N_TRACKED_ELEMENTS + 1
     DO NE = JR+1, N_TRACKED_ELEMENTS
         KK = ELEMENTS_ORDER(NE)
         IF (EABUND(KK) /= USEDBEFORE .AND. EABUND(KK) > 0.0_EB) THEN
             K = NE
             EXIT
         END IF
     END DO

     ! Pick any remaining element if none positive
     IF (K > N_TRACKED_ELEMENTS) THEN
         DO NE = JR+1, N_TRACKED_ELEMENTS
             KK = ELEMENTS_ORDER(NE)
             IF (EABUND(KK) /= USEDBEFORE) THEN
                 K = NE
                 EXIT
             END IF
         END DO
     END IF

     ! Error if not enough independent elements
     IF (K > N_TRACKED_ELEMENTS) THEN
         PRINT *, "Error: Not enough independent elements"
         STOP
     END IF

     KK = ELEMENTS_ORDER(K)
     EABUND(KK) = USEDBEFORE

     ! Fill SM row for this element (with component species)
     DO NS = 1, N_COMPONENTS
         SM(NS, JR+1) = SPECIES_MIXTURE(SPECIES_ORDER(NS))%ATOMS(TRACKED_ELEM_INDX(KK))
     END DO

     ! Modified Gram-Schmidt
     JL = JR
     IF (JL > 0) THEN
         DO NE = 1, JL
             SS(NE) = 0.0_EB
             DO NS = 1, N_COMPONENTS
                 SS(NE) = SS(NE) + SM(NS, JR+1) * SM(NS, NE)
             END DO
             SS(NE) = SS(NE) / SA(NE)

             DO NS = 1, N_COMPONENTS
                 SM(NS, JR+1) = SM(NS, JR+1) - SS(NE) * SM(NS, NE)
             END DO
         END DO
     END IF

     ! Compute norm
     SA(JR+1) = 0.0_EB
     DO ML = 1, N_COMPONENTS
         SA(JR+1) = SA(JR+1) + SM(ML, JR+1)**2
     END DO

     ! Accept if not too small
     IF (SA(JR+1) > TOL) THEN
         ! Swap into JR position
         IF (JR+1 /= K) THEN
             DUMMY_INT = ELEMENTS_ORDER(JR+1)
             ELEMENTS_ORDER(JR+1) = ELEMENTS_ORDER(K)
             ELEMENTS_ORDER(K) = DUMMY_INT
         END IF
         JR = JR + 1
     END IF
   END DO

END SUBROUTINE ELEMREARRANGE



! Solve the Stoichimetric equations assuming Constant Volume (density) and First fixed variable (enthalpy or internal energy).
SUBROUTINE SET_APPROXIMATE_INITIAL_MOLES_SOLUTION(XX,TMP_IN,PRES_IN,TMP_OUT,PRES_OUT,EQ_OPTION)
   USE PHYSICAL_FUNCTIONS, ONLY : GET_MOLECULAR_WEIGHT_FROM_MOLE_FRACTIONS

   REAL(EB), INTENT(INOUT) :: XX(N_TRACKED_SPECIES)
   REAL(EB), INTENT(IN)    :: TMP_IN,PRES_IN
   REAL(EB), INTENT(OUT)    :: TMP_OUT,PRES_OUT
   TYPE(EQUILIBRIUM_OPTION), INTENT(IN) :: EQ_OPTION
   
   INTEGER  :: ITER
   REAL(EB) :: MIN_ALLOWED_TMP,MAX_ALLOWED_TMP,TMIN,TMAX,PRMIN,PRMAX,RHO,MW
   REAL(EB) :: VAR_LOW,VAR_HIGH,VAR_VAL,FIXED_FIRST_VAR,TMP0,DTMP,PRES_IT,SLOPE


   MIN_ALLOWED_TMP=300.0_EB
   MAX_ALLOWED_TMP=5000.0_EB !REAL(I_MAX_TEMP)

   TMIN = MAX(TMP_IN, MIN_ALLOWED_TMP)
   IF (TMIN > MAX_ALLOWED_TMP) THEN
       TMIN = MAX_ALLOWED_TMP - 20._EB
   END IF
   TMAX = MIN(TMIN + 10._EB, MAX_ALLOWED_TMP)
   IF (TMAX < MIN_ALLOWED_TMP) THEN
       TMAX = MIN_ALLOWED_TMP + 20._EB
   END IF

   
   IF (N_TRACKED_SPECIES .LT. N_TRACKED_ELEMENTS) THEN
      ! This alogorithm only works when number of species is more than number of elements, which is mostly the case.
      RETURN
   ENDIF

   CALL GET_MOLECULAR_WEIGHT_FROM_MOLE_FRACTIONS(XX,MW)
   RHO = PRES_IN*MW/R0/TMP_IN

   PRMAX = RHO/MW*R0*TMAX
   CALL SET_INITIAL_MOLES_BASED_ON_STOICHIOMETRY(XX,TMAX,PRMAX) ! Min temp
   CALL GET_FIRST_VAR_VAL(XX,TMAX,PRMAX,EQ_OPTION,VAR_HIGH)
   
   PRMIN = RHO/MW*R0*TMIN
   CALL SET_INITIAL_MOLES_BASED_ON_STOICHIOMETRY(XX,TMIN,PRMIN) ! Max temp
   CALL GET_FIRST_VAR_VAL(XX,TMIN,PRMIN,EQ_OPTION,VAR_LOW)
   
   CALL GET_FIRST_FIXED_VAL(EQ_OPTION,FIXED_FIRST_VAR) 
   TMP0 = 0.5_EB * (TMIN + TMAX)

   DO ITER = 1, 10

      PRES_IT = RHO / MW * R0 * TMP0
      CALL SET_INITIAL_MOLES_BASED_ON_STOICHIOMETRY(XX, TMP0, PRES_IT)
      CALL GET_FIRST_VAR_VAL(XX, TMP0, PRES_IT, EQ_OPTION, VAR_VAL)

      ! --- Update bracket ---
      IF (VAR_VAL > FIXED_FIRST_VAR) THEN
         TMAX = TMP0
         VAR_HIGH = VAR_VAL
      ELSE
         TMIN = TMP0
         VAR_LOW = VAR_VAL
      END IF

      ! --- Linear interpolation (secant step) ---
      SLOPE = (VAR_HIGH - VAR_LOW) / (TMAX - TMIN)
      DTMP = (FIXED_FIRST_VAR - VAR_VAL) / SLOPE
      IF (ABS(DTMP) < 50._EB) EXIT

      DTMP = MAX(-200._EB, MIN(200._EB, DTMP))
      IF (TMP0 + DTMP < MIN_ALLOWED_TMP) THEN
         DTMP = 0.5_EB * (TMP0 + MIN_ALLOWED_TMP) - TMP0
      END IF
      IF (TMP0 + DTMP > MAX_ALLOWED_TMP) THEN
         DTMP = 0.5_EB * (TMP0 + MAX_ALLOWED_TMP) - TMP0
      END IF

      ! --- Update temperature ---
      TMP0 = TMP0 + DTMP
      IF (TMP0 <= MIN_ALLOWED_TMP .OR. TMP0 >= MAX_ALLOWED_TMP .OR. TMP0 < 100._EB) THEN
         WRITE(LU_ERR,*) "ERROR: Temperature out of bounds:", TMP0
         RETURN
      END IF

   END DO

   TMP_OUT = TMP0
   PRES_OUT = RHO / MW * R0 * TMP_OUT

END SUBROUTINE SET_APPROXIMATE_INITIAL_MOLES_SOLUTION

SUBROUTINE GET_FIRST_VAR_VAL(XX,TMP,PRES,EQ_OPTION,VAL)
   USE PHYSICAL_FUNCTIONS, ONLY :  GET_MOLECULAR_WEIGHT, MOLE_FRAC_TO_MASS_FRAC, GET_ENTHALPY

   REAL(EB), INTENT(IN) :: XX(N_TRACKED_SPECIES),TMP,PRES
   TYPE(EQUILIBRIUM_OPTION), INTENT(IN) :: EQ_OPTION
   REAL(EB), INTENT(OUT) :: VAL

   REAL(EB) :: ZZ(N_TRACKED_SPECIES),MW

   CALL MOLE_FRAC_TO_MASS_FRAC(XX,ZZ)
   CALL GET_MOLECULAR_WEIGHT(ZZ,MW)

   IF(DEBUG) WRITE(LU_ERR,*)"PRES=",PRES

   IF (EQ_OPTION%OPTION .EQ. 1) THEN ! FIXED HP
      CALL GET_ENTHALPY(ZZ,VAL,TMP)
   ELSE ! FIXED UV
      CALL GET_ENTHALPY(ZZ,VAL,TMP)
      VAL = VAL - R0*TMP/MW ! J/kmol
   ENDIF
END SUBROUTINE GET_FIRST_VAR_VAL

SUBROUTINE GET_SECOND_VAR_VAL(XX,TMP,PRES,EQ_OPTION,VAL)
   USE PHYSICAL_FUNCTIONS, ONLY :  GET_MOLECULAR_WEIGHT_FROM_MOLE_FRACTIONS

   REAL(EB), INTENT(IN) :: XX(N_TRACKED_SPECIES),TMP,PRES
   TYPE(EQUILIBRIUM_OPTION), INTENT(IN) :: EQ_OPTION
   REAL(EB), INTENT(OUT) :: VAL
   REAL(EB) :: MW

   CALL GET_MOLECULAR_WEIGHT_FROM_MOLE_FRACTIONS(XX,MW)

   IF (EQ_OPTION%OPTION .EQ. 1) THEN ! FIXED HP
      VAL = PRES
   ELSE ! FIXED UV
      VAL = PRES*MW/R0/TMP
   ENDIF
END SUBROUTINE GET_SECOND_VAR_VAL

SUBROUTINE GET_FIRST_FIXED_VAL(EQ_OPTION,VAL)
   USE PHYSICAL_FUNCTIONS, ONLY :  GET_MOLECULAR_WEIGHT, MOLE_FRAC_TO_MASS_FRAC, GET_ENTHALPY

   TYPE(EQUILIBRIUM_OPTION), INTENT(IN) :: EQ_OPTION
   REAL(EB), INTENT(OUT) :: VAL

   IF (EQ_OPTION%OPTION .EQ. 1) THEN ! FIXED HP
      VAL=EQ_OPTION%FIXED_ENTH
   ELSE ! FIXED UV
      VAL=EQ_OPTION%FIXED_INT_ENG
   ENDIF
END SUBROUTINE GET_FIRST_FIXED_VAL

SUBROUTINE GET_SECOND_FIXED_VAL(EQ_OPTION,VAL)
   USE PHYSICAL_FUNCTIONS, ONLY :  GET_MOLECULAR_WEIGHT, MOLE_FRAC_TO_MASS_FRAC, GET_ENTHALPY

   TYPE(EQUILIBRIUM_OPTION), INTENT(IN) :: EQ_OPTION
   REAL(EB), INTENT(OUT) :: VAL

   IF (EQ_OPTION%OPTION .EQ. 1) THEN ! FIXED HP
      VAL=EQ_OPTION%FIXED_PRES
   ELSE ! FIXED UV
      VAL=EQ_OPTION%FIXED_RHO
   ENDIF
END SUBROUTINE GET_SECOND_FIXED_VAL

SUBROUTINE SET_INITIAL_MOLES_BASED_ON_STOICHIOMETRY(XX,TMP,PRES)
   USE PHYSICAL_FUNCTIONS, ONLY : GET_GIBBS_ENERGY_Z_INTERP

   REAL(EB), INTENT(IN) :: TMP, PRES
   REAL(EB), INTENT(INOUT) :: XX(N_TRACKED_SPECIES)
   
   INTEGER  :: N_FREE
   REAL(EB) :: MU(N_TRACKED_SPECIES) 
   REAL(EB) :: STOICH_MAT(N_TRACKED_SPECIES,N_TRACKED_SPECIES-N_TRACKED_ELEMENTS) 
   REAL(EB) :: DG_RT,DELTA_XI,DIR,NU,DXI_MIN
   INTEGER  :: NF,NS,ITER
   LOGICAL :: REDO

   N_FREE = N_TRACKED_SPECIES-N_TRACKED_ELEMENTS
   MU = 0.0_EB ! Chemical potential
   DO NS = 1, N_TRACKED_SPECIES
      CALL GET_GIBBS_ENERGY_Z_INTERP(NS,MU(NS),TMP,PRES)
      !WRITE(LU_ERR,*)"ID,MU,XX=",SPECIES_MIXTURE(NS)%ID,MU(NS),XX(NS)
   END DO

   REDO = .TRUE.
   ITER = 0
   DO WHILE(REDO)
      CALL COMPUTE_STOICH_MATRIX(XX,STOICH_MAT)
      REDO = .FALSE.
      ITER = ITER +1
      IF (ITER > 4) EXIT

      DO NF = 1, N_FREE
         DG_RT = 0.0
         DXI_MIN = 1.0E10_EB

         DO NS = 1, N_TRACKED_SPECIES
            DG_RT = DG_RT + MU(NS) * STOICH_MAT(NS, NF)
         END DO
         !WRITE(LU_ERR,*)"DG_RT=",DG_RT

         IF (DG_RT < 0.0) THEN
            DIR = 1.0_EB
         ELSE
            DIR = -1.0_EB
         END IF

         DO NS = 1, N_TRACKED_SPECIES
            NU = STOICH_MAT(NS, NF)
            IF (NU * DIR < 0.0) THEN
                DELTA_XI = ABS(0.99 * XX(NS) / NU)

                IF (.NOT. REDO .AND. DELTA_XI .LT. 1.0E-10_EB .AND. NS .LE. N_TRACKED_ELEMENTS) THEN
                    REDO = .TRUE.
                END IF
                DXI_MIN = MIN(DXI_MIN,DELTA_XI)
            END IF
         END DO

         DO NS = 1, N_TRACKED_SPECIES
            XX(NS) = XX(NS) + STOICH_MAT(NS, NF) * DIR * DXI_MIN
         END DO
      ENDDO  
      CALL UPDATE_MOLE_FRACTIONS(XX)

   ENDDO

END SUBROUTINE SET_INITIAL_MOLES_BASED_ON_STOICHIOMETRY

SUBROUTINE UPDATE_MOLE_FRACTIONS(XX)
   REAL(EB), INTENT(INOUT) :: XX(N_TRACKED_SPECIES)
   REAL(EB) :: SUMXX

   WHERE (XX < 0._EB) XX = 0._EB
   SUMXX = SUM(XX)

   IF (SUMXX > 0._EB) THEN
      XX = XX / SUMXX
   ELSE
      ! ERROR
      WRITE(LU_ERR,*)" Error: Failure in Equilibrium logic. Stopping FDS."
      STOP
   END IF
END SUBROUTINE UPDATE_MOLE_FRACTIONS


SUBROUTINE COMPUTE_STOICH_MATRIX(XX,STOICH_MAT)
   REAL(EB), INTENT(IN) :: XX(N_TRACKED_SPECIES)
   REAL(EB), INTENT(OUT) :: STOICH_MAT(N_TRACKED_SPECIES,N_TRACKED_SPECIES-N_TRACKED_ELEMENTS) 
   
   INTEGER :: SPECIES_ORDER(N_TRACKED_SPECIES)
   
   INTEGER  :: N_FREE   
   REAL(EB) :: FORMULA_MAT(N_TRACKED_ELEMENTS,N_TRACKED_SPECIES)
   REAL(EB) :: DUMMY_REAL,MAXMOLES 
   INTEGER  :: NE,NS,ELEM_INDX,NE1,NS1,DUMMY_INT,NS_MAX
   INTEGER :: I, J, IMAX
   REAL(EB) :: XMAX

   N_FREE = N_TRACKED_SPECIES-N_TRACKED_ELEMENTS

   DO NS = 1, N_TRACKED_SPECIES
      SPECIES_ORDER(NS) = NS
   END DO

   ! SORT SPECIES ORDER (DESCENDING ORDER)
   DO I = 1, N_TRACKED_SPECIES-1
      IMAX = I
      XMAX = XX(SPECIES_ORDER(I))

      DO J = I+1, N_TRACKED_SPECIES
         IF (XX(SPECIES_ORDER(J)) > XMAX) THEN
            IMAX = J
            XMAX = XX(SPECIES_ORDER(J))
         END IF
      END DO

      ! SWAP INDICES
      IF (IMAX /= I) THEN
         DUMMY_INT = SPECIES_ORDER(I)
         SPECIES_ORDER(I) = SPECIES_ORDER(IMAX)
         SPECIES_ORDER(IMAX) = DUMMY_INT
      END IF
   END DO

   
   DO NE = 1, N_TRACKED_ELEMENTS
      ELEM_INDX = TRACKED_ELEM_INDX(NE)
      DO NS = 1, N_TRACKED_SPECIES
         FORMULA_MAT(NE, NS) = SPECIES_MIXTURE(SPECIES_ORDER(NS))%ATOMS(ELEM_INDX)
      END DO
   END DO

   ! Form the vector of linear independent reactions
   ! 1. Gaussian elimination with column pivoting (species with max moles are in the diagonal column)
   ! 2. Construct the stoichiometric reaction matrix
   STOICH_MAT = 0._EB
   DO NE = 1, N_TRACKED_ELEMENTS
      IF (NE <= N_TRACKED_ELEMENTS) THEN
         MAXMOLES = -100._EB
         NS_MAX = NE
         DO NS = NE, N_TRACKED_SPECIES
            IF (FORMULA_MAT(NE,NS) /= 0.0_EB .AND. ABS(XX(SPECIES_ORDER(NS))) > MAXMOLES) THEN
                NS_MAX = NS
                MAXMOLES = ABS(XX(SPECIES_ORDER(NS)))
            END IF
         END DO

         DO NE1 = 1, N_TRACKED_ELEMENTS
            DUMMY_REAL = FORMULA_MAT(NE1,NE)
            FORMULA_MAT(NE1,NE) = FORMULA_MAT(NE1,NS_MAX)
            FORMULA_MAT(NE1,NS_MAX) = DUMMY_REAL
         END DO

         DUMMY_INT = SPECIES_ORDER(NE)
         SPECIES_ORDER(NE) = SPECIES_ORDER(NS_MAX)
         SPECIES_ORDER(NS_MAX) = DUMMY_INT
      END IF

      ! Scale Row Ne To Make Pivot 1
      DUMMY_REAL = FORMULA_MAT(NE,NE)
      IF (ABS(DUMMY_REAL) < 1.0D-12) CYCLE
      DO NS = 1, N_TRACKED_SPECIES
         FORMULA_MAT(NE,NS) = FORMULA_MAT(NE,NS) / DUMMY_REAL
      END DO

      ! Eliminate Below
      DO NE1 = NE+1, N_TRACKED_ELEMENTS
         DUMMY_REAL = FORMULA_MAT(NE1,NE)
         DO NS = 1, N_TRACKED_SPECIES
            FORMULA_MAT(NE1,NS) = FORMULA_MAT(NE1,NS) - &
                       DUMMY_REAL * FORMULA_MAT(NE,NS)
         END DO
      END DO
   END DO

   
   ! Back-Substitution 
   DO NE = N_TRACKED_ELEMENTS, 1, -1
       DO NE1 = NE-1, 1, -1
           IF (FORMULA_MAT(NE1,NE) /= 0.0_EB) THEN
               DUMMY_REAL = FORMULA_MAT(NE1,NE)
               DO NS = NE, N_TRACKED_SPECIES
                   FORMULA_MAT(NE1,NS) = FORMULA_MAT(NE1,NS) - &
                          DUMMY_REAL * FORMULA_MAT(NE,NS)
               END DO
           END IF
       END DO
   END DO

   ! Construct Stoichiometric Matrix 
   DO NS = 1, N_TRACKED_SPECIES
       IF (NS .LE. N_TRACKED_ELEMENTS) THEN
           DO NS1 = 1, N_FREE
               STOICH_MAT(SPECIES_ORDER(NS), NS1) = -FORMULA_MAT(NS, NS1 + N_TRACKED_ELEMENTS)
           END DO
       ELSE
           DO NS1 = 1, N_FREE
               STOICH_MAT(SPECIES_ORDER(NS), NS1) = 0.0_EB
           END DO
           STOICH_MAT(SPECIES_ORDER(NS), NS - N_TRACKED_ELEMENTS) = 1.0_EB
       END IF
   END DO

END SUBROUTINE COMPUTE_STOICH_MATRIX



END MODULE CHEM_EQUIL

!> @cond DOXYGEN_IGNORE
#endif
!> @endcond

